### ISSUE TITLE
Desktop shortcut for games

### ISSUE THREAD

**Issue by Renzo904** [TcNobo/TcNo-Acc-Switcher#10]
I know that i can create a desktop shortcut to switch the account, but its possible do a shortcut directly for the games? i mean, open it, and in addition to switch the acc, execute the game

**Comment by TcNobo** [comment]
Yes, this is a planned feature. Started work on implementing it :)

**Comment by Renzo904** [comment]
Ohh, I see it, ty :)

**Comment by aburakayaz** [comment]
I definitely need this feature :)

**Comment by TcNobo** [comment]
A similar feature is coming soon in the next major update. I'm closing this for now to clean up issues.

**Comment by SahajJain01** [comment]
Sorry if I missed it in Wiki, but how can I create a shortcut for game specific to a steam account which switches to that steam account and launches the game.

**Comment by TcNobo** [comment]
There isn't a 'switch and launch' feature, but it now picks up shortcuts from the platform's folder on the start menu that you can click to launch, as well as click the `+` to add your own/more apps, games and programs.
