### ISSUE TITLE
Tray failed to start on boot

### ISSUE THREAD

**Issue by uselessbug** [TcNobo/TcNo-Acc-Switcher#100]
I've set as below, but tray still failed to start with Windows.
![图片](https://user-images.githubusercontent.com/61285640/142992434-dd39be64-6476-46f4-9f96-73326243f0cd.png)

Checked the tskmgr, no relevant item found.
![图片](https://user-images.githubusercontent.com/61285640/142992985-0a0b5a95-4634-423c-8ded-9257601203de.png)

**Comment by TcNobo** [comment]
If you click `[Start Tray Now]` what happens? Is there an error?
-
Press Start > Open: Event Viewer > Navigate into Windows Logs > Application, do you see any .NET or TcNo related errors? If so please post them here.

**Comment by uselessbug** [comment]
> If you click `[Start Tray Now]` what happens? Is there an error?
No there's no error. I'll check the event viewer tomorrow.

**Comment by uselessbug** [comment]
> Press Start > Open: Event Viewer > Navigate into Windows Logs > Application, do you see any .NET or TcNo related errors? If so please post them here.

Also no error found in Event Viewer

**Comment by TcNobo** [comment]
I've moved it from a Task to just a shortcut in your Startup folder. This should fix issues on some computers, as it's a lot simpler and shouldn't require admin at all to set up.
It should be fixed in the next update.

**Comment by TcNobo** [comment]
I'm closing this as it should be fixed. Feel free to reopen if you experience further issues :)
