### ISSUE TITLE
Can't find EpicGamesLauncher.exe

### ISSUE THREAD

**Issue by CarMarch** [TcNobo/TcNo-Acc-Switcher#101]
I located and have found the EpicGmaesLuancher.exe file path but the account switcher still can not even when I manually enter the file path

**Comment by TcNobo** [comment]
I can't recreate this, so I'm not able to solve what's causing this.

Epic Games installed to: `D:\Epic\Epic Games\Launcher\Engine\Binaries\Win64\EpicGamesLauncher.exe`

When I click Epic Games in the TcNo Account Switcher, then `Locate EpicGamesLauncher.exe`, head to the folder mentioned above, select `EpicGamesLauncher.exe`, click `Open`.
The window now has "`D:\Epic\Epic Games\Launcher\Engine\Binaries\Win64`" in the text box.
I then click `Select Epic folder`.
(The next update will automatically put you into the requested switcher without having to click the icon twice)
And then it works..

After restarting my computer, the program or both it just remembers it.

It is saved in: `%AppData%\TcNo Account Switcher\EpicSettings.json` as the following line:
`  "FolderPath": "C:\\Program Files (x86)\\Epic Games\\Launcher\\Portal\\Binaries\\Win32\\"`

------
Some things that I can think of:
- Make sure the program has permissions to access EpicGamesLauncher.exe and it's folder
- Make sure the program has access to save to `%AppData%\TcNo Account Switcher\EpicSettings.json` -- Check if this updates after you set the Epic Games path.


If you can, provide more details so I can recreate the issue myself.

**Comment by TcNobo** [comment]
Closing assuming this was fixed. I do remember fixing something like this at a stage, and it should definitely be fixed with the next major update. See the post I'm linking below this post.
