### ISSUE TITLE
Stuck "Closing Discord" or "Initialising"

### ISSUE THREAD

**Issue by T0talInsan1ty** [TcNobo/TcNo-Acc-Switcher#102]
As title says, discord account switcher keeps getting stuck on either "Closing Discord" or when opening discord and then trying to swap it goes to "Initialising" and then "Ready" which it then stays on. Nothing is even opening.

I've made sure to close discord via task manager and other ways, reinstalled discord, restarted TCNO account switcher, restarted whole PC and still the same issue. Not really sure what's causing this as it has been working fine for a day or so prior to this issue. Should also mention i'm definitely not logged in on browser.

**Comment by TcNobo** [comment]
Please see the post linked above. The problem/s you've mentioned should be fixed with the next major update.
This issue is being closed and cleaned to prevent a flood of "x broken" posts.
