### ISSUE TITLE
Open directly to steam

### ISSUE THREAD

**Issue by cyberbug-2077** [TcNobo/TcNo-Acc-Switcher#103]
Hi, can you add setting to make it open directly to steam?

**Comment by TcNobo** [comment]
On the main screen, Right-Click Steam and you can create a shortcut to open right to the Steam switcher.
You can also edit the shortcut to include `steam` after the .exe to achieve the same thing. See the shortcut created by the above.
![image](https://user-images.githubusercontent.com/10319195/144017000-fe7a1e56-c261-4d61-a80d-d3ee9605c202.png)
