### ISSUE TITLE
Can't start tray with windows or start tray now.

### ISSUE THREAD

**Issue by supertrio17** [TcNobo/TcNo-Acc-Switcher#105]
Hi, so I used this program a while now, since version 2 something and recently upgraded to version 4.1, but program won't start when starting my pc. I looked inside TcNo created task and found that tray file is located inside %appdata%, but when manually looking inside the "AppData\Roaming\TcNo Account Switcher" there is no file called "TcNo-Acc-Switcher-Tray.exe", there is no .exe file there. I tried uninstalling multiple times with no luck, any help?

Edit: One thing you might want to fix, when updating from older version (mine was 2.7 or something) by uninstalling old one, the tasks don't get deleted. I came to conclusion that newer version of Acc Switcher thinks that start with tray task is already created and doesn't create task with new file location.

**Comment by TcNobo** [comment]
Fixed.
Can't remember why I used tasks for this when the startup folder exists to be honest.
I've removed the Task functionality, and instead started using the normal starutp folder with a shortcut. Should be more reliable, and let users control it from the Task Manager as well. This will come with the next update.

**Comment by supertrio17** [comment]
Is it possible for you to push a new release containing this changes, I can't compile it in my VS for some reason, it gives me bunch of errors.

**Comment by TcNobo** [comment]
Yes, I'm busy adding finishing touches now and it should be released in a few hours, if not tomorrow.

**Comment by supertrio17** [comment]
Thanks :)

**Comment by TcNobo** [comment]
The reason this update is taking so long, and likely the reason you can't build it is that now it's all set up for .NET 6.
Building should be users can do, and used to be able to do - I'll look into this at a later date.
