### ISSUE TITLE
Uplay

### ISSUE THREAD

**Issue by Dogge59** [TcNobo/TcNo-Acc-Switcher#11]
I know this isnt an issue but i didnt find any other way to message you. I just wanted to say this works flawlessly and that me and i would imagine many others would love to see an account switcher for Uplay.

**Comment by TcNobo** [comment]
I have already worked out how Origin works, so an account switcher is "easy" to make for that. I am absolutely planning to add functionality for other platforms.
The way I've coded it I don't find easy to work with, so adding small changes takes a while. I've decided to dive into C# + Electron, to have the same functionality, but ease of creating UI. Electron is what runs Discord, for example.
A better looking UI, that's easier to add functionality to. It's just going to take a while to learn it and get it working, though development has started.

**Comment by TcNobo** [comment]
This is now implemented in the latest Beta version.

You can get access to it through the community Discord: https://s.tcno.co/AccSwitcherDiscord
(See #updates and #general-acc-switcher)
Let me know how your experience with the beta is. Need to find and work out some bugs I may have missed.
