### ISSUE TITLE
Processes don't get killed when going to tray

### ISSUE THREAD

**Issue by supertrio17** [TcNobo/TcNo-Acc-Switcher#111]
So, after installing everything works fine, program goes to tray without any problems, but when trying to open app from tray by double clicking it says that another instances have been detected. After closing to tray, it doesn't kill the main process as it should.
![image](https://user-images.githubusercontent.com/57882120/145288699-3714627d-a7d3-4775-96a5-0b2e3d77fb44.png)

**Comment by TcNobo** [comment]
Thanks, forgot about this when working around other issues. Will get to solving it :)

**Comment by TcNobo** [comment]
The program killed related processes as they were related. Now it launches the .NET verifier, which launches the acutal program, breaking the link.
I've added a command to close all processes that have `TcNo-Acc-Switcher` in them when it exits, which should result in the same thing.
