### ISSUE TITLE
can't update

### ISSUE THREAD

**Issue by zak0vich** [TcNobo/TcNo-Acc-Switcher#115]
when i press on update avilable ! click here to start 
got red messege " faild to cheack for update "

**Comment by TcNobo** [comment]
Start it, click the `?` in the bottom right. What version are you on? Where is it installed to? This info should help me fix it, if there's an issue. 2021-12-06_00's updater was broken.

As for fixing the issue immediately: Download a fresh copy from the GitHub here and either install it again (if you installed it the first time), or download the .7z or .zip and replace your current files.

**Comment by zak0vich** [comment]
> Start it, click the `?` in the bottom right. What version are you on? Where is it installed to? This info should help me fix it, if there's an issue. 2021-12-06_00's updater was broken.
> 
> As for fixing the issue immediately: Download a fresh copy from the GitHub here and either install it again (if you installed it the first time), or download the .7z or .zip and replace your current files.

thanks for replay ,, problem solve after pc restart and reinstall netframework 6

**Comment by TcNobo** [comment]
Awesome, glad it's fixed :)
