### ISSUE TITLE
Origin doesn't work

### ISSUE THREAD

**Issue by BlackOfWorld** [TcNobo/TcNo-Acc-Switcher#119]
I tried selecting Origin.exe, but it just doesn't accept it. Sometimes it also crashes and upon relaunching it display this error:
https://i.imgur.com/5hlV0zT.png

**Comment by TcNobo** [comment]
Please see the post linked above. The problem/s you've mentioned should be fixed with the next major update.
This issue is being closed and cleaned to prevent a flood of "x broken" posts.

**Comment by BlackOfWorld** [comment]
Thanks!
