### ISSUE TITLE
Error when opening discord account switcher

### ISSUE THREAD

**Issue by Uphorium** [TcNobo/TcNo-Acc-Switcher#121]
Same issue as Issue #70 except reinstalling discord doesn't help. I have also reinstalled TCNO switcher. BetterDiscord is installed as well.
![image](https://user-images.githubusercontent.com/25294600/146874401-f3177cd0-2bcf-463b-95f0-265402379770.png)

**Comment by TcNobo** [comment]
Please see the post linked above. The problem/s you've mentioned should be fixed with the next major update.
This issue is being closed and cleaned to prevent a flood of "x broken" posts.
