### ISSUE TITLE
Minimize to tray

### ISSUE THREAD

**Issue by cyberbug-2077** [TcNobo/TcNo-Acc-Switcher#123]
Hey, can you make min to tray? And maybe can change the account with right click on tray too

**Comment by TcNobo** [comment]
Both of these features exist already:
In settings:
![image](https://user-images.githubusercontent.com/10319195/147461485-451e1794-9957-4612-aaa6-e22cd2905bab.png)
In tray:
![image](https://user-images.githubusercontent.com/10319195/147461511-768f9357-78e2-4c15-899e-4addc0c7ca85.png)

Make sure you're up-to-date for the latest features :)
