### ISSUE TITLE
Overwatch setting not working

### ISSUE THREAD

**Issue by tired9494** [TcNobo/TcNo-Acc-Switcher#128]
The BattleNet switcher has an option for Overwatch SR and Overwatch PFPs but neither work for me, they don't even show the battlenet profile pictures either. I tried logging in while account switcher was on, I tried launching overwatch, and I also tried the "refetch rank" option when right clicking a profile but none of it worked.

![battlenet](https://user-images.githubusercontent.com/22395617/148087837-a0eb7302-4caa-42fa-93d0-d54e3c1ac7e5.png)

**Comment by TcNobo** [comment]
I don't have the ability to test this, unfortunately... @HoeblingerDaniel do you still play Overwatch and use the TcNo Account Switcher? Has anything changed with the API you used? If you know what has changed I can try and look at it :)

**Comment by HoeblingerDaniel** [comment]
In order for it to work you need to Right Click > Set BattleTag. I just tried it and it works fine for me.

**Comment by tired9494** [comment]
Thought I already tried that but it works now, thank you
