### ISSUE TITLE
Cannot create shortcut.

### ISSUE THREAD

**Issue by CPPPt** [TcNobo/TcNo-Acc-Switcher#13]
It shows that the shortcut is successfully created, but when I go back to my desktop there is nothing.
What's the problem?

**Comment by CPPPt** [comment]
Or is there any way to manually do it?

**Comment by CPPPt** [comment]
Fixed my manually doing this, add a shortcut like this "C:\Program Files\TcNo Account Switcher\Steam\TcNo Account Switcher Steam.exe" +76561198064588130(Steam ID)

**Comment by TcNobo** [comment]
Solved through Discord.
No idea why it's not creating shortcuts.
Shortcut to open the Steam switcher: `"C:\Program Files\TcNo Account Switcher\TcNo Account Switcher.exe" +steam`
Switch to a specific account: `"C:\Program Files\TcNo Account Switcher\Steam\TcNo Account Switcher Steam.exe" +76561198064588130`
