### ISSUE TITLE
Learn how to english

### ISSUE THREAD

**Issue by TheDingOfTheHud** [TcNobo/TcNo-Acc-Switcher#130]
![image](https://user-images.githubusercontent.com/62679764/148639967-ef468b69-3a0e-4336-acbb-3550b7966fa6.png)
THANHS

It's Thanks not Thanhs 

Please fix this for my OCD

ty

**Comment by TcNobo** [comment]
The font in question is [Septhcharge](https://www.dafont.com/septacharge.font?text=THANKS).
There is a small difference between H and K
![chrome_GWupTrBp0T](https://user-images.githubusercontent.com/10319195/148640994-77fefd07-8eca-4f62-ab66-c0743322ff50.png)

If anything it's exaggerated by antialiasing. I've changed it regardless. It should take some time to reflect, I assume. https://github.com/TcNobo/TcNo-Acc-Switcher/commit/019f8561be98e178040377de57872d69b45fd2cf.
