### ISSUE TITLE
Account Switcher not working for Valorant

### ISSUE THREAD

**Issue by unkn0wn234** [TcNobo/TcNo-Acc-Switcher#133]
Stopped working after the new Valorant update not sure if that has anything to do with it. I readded both accounts to the switcher as well; no avail. It works fine when switching to my League account but not for Valorant. When switching to Valorant and then opening Valorant it just takes me to the account login screen rather than already being logged in like it should.

I couldn't find a logs setting in the TCNO settings can you tell me where I can find logs if there are any so I can put it here?

**Comment by unkn0wn234** [comment]
Found the log attaching it below
[log.txt](https://github.com/TcNobo/TcNo-Acc-Switcher/files/7859151/log.txt)

**Comment by TcNobo** [comment]
Please see the post linked above. The problem/s you've mentioned should be fixed with the next major update.
This issue is being closed and cleaned to prevent a flood of "x broken" posts.

**Comment by unkn0wn234** [comment]
> Please see the post linked above. The problem/s you've mentioned should be fixed with the next major update.
> This issue is being closed and cleaned to prevent a flood of "x broken" posts.

Sorry for the flooding, thanks for the update I look forward to when it releases! Thanks again for the work you put into this I know it’s not easy to make something for free and I and the rest of the users appreciate it a lot
