### ISSUE TITLE
Discord account switcher not working

### ISSUE THREAD

**Issue by supertrio17** [TcNobo/TcNo-Acc-Switcher#134]
Hey, so discord account switcher doesn't seem to work, It just closes my discord when I try to add new account, and this is everything it shows
![image](https://user-images.githubusercontent.com/57882120/149779823-aad9fd9f-10c3-4783-9e39-a106de0f3ffa.png)

**Comment by TcNobo** [comment]
Please see the post linked above. The problem/s you've mentioned should be fixed with the next major update.
This issue is being closed and cleaned to prevent a flood of "x broken" posts.

**Comment by TcNobo** [comment]
Oh and while this isn't specifically the issue I'm mentioning above, it does tie in, and this is something that should be fixed too :)
