### ISSUE TITLE
<Platform> is not working?!?! (Updates, and when to expect a fix)

### ISSUE THREAD

**Issue by TcNobo** [TcNobo/TcNo-Acc-Switcher#135]
# An update
Hi. So I've got a lot of complaints about the X platform and the Y platform not working. Yes, I am working on a fix. Yes, it is coming very soon with a MAJOR update. I'm talking about leaving Beta levels of update.

This post was created to collate and end the creation of new "X platform is BROKEN!?!?!!" threads. If you were told to look at this issue before yours was closed, the platform you reported an issue for has a fix coming. Existing issues will be mentioned at the end of the post.

Let's get into it.

## Why are things breaking?
Simple. Some platforms update which files they store data in, or how they store it. Admittedly I have over-engineered some aspects of this program. The original vision was to design this software as 'modular'. You simply tell it what files/registry keys, a program name and send it on its way. For the past year or so I've been thinking of a way to do this, and admittedly overthinking and over-engineering a solution. With burnout on this completely free magnum opus project of mine reaching an all-time high, it's been rough. I've curtailed coding a shop I'm setting up among other things to completely focus on this project to get it to a state the community can more easily manage.

Those who have committed code to this project understand how spaghettified the code is. I started knowing 0 about C# from coding VB.NET only. Since then I have come from novice to where I am now. While some of the code has been cleaned, a lot is still everywhere. I have no idea how @HoeblingerDaniel got their mind around my messy code to create the Battle.Net switcher, but well done and thank you again.

## What's changing?
Many things. There is a new "Basic Platform" architecture. A simple text file (JSON). While it needs some level of code know-how, it can be edited and maintained in Notepad if you wish. Add files, registry entries and tune every platform that's based on this to your heart's desire. The Steam switcher has remained one of the only platforms with a 99.999% uptime and is the most reliable. Everything else breaks here and there. I'm busy putting the finishing touches on this and moving as much as I can to it to simplify everything. I can only see Steam and Battle.Net being left behind and needing to be hardcoded due to their VAC Status and Overwatch rank capability (which I hear the latter is broken anyways).

I do plan on implementing a "plugin" system in the future, for more advanced features. Providing endpoints like "AccSwitchStart" and "AccSwitchEnd", etc, to allow users to add their own functionality to the program. I have no idea how to go about this and is as much of a pipe dream at this point as this simplified 'templated system' I'm discussing in this post.

## How do I help?
As I mentioned, it's a simple text-based JSON file. Find it here: [BasicPlatforms.json](https://github.com/TcNobo/TcNo-Acc-Switcher/blob/master/TcNo-Acc-Switcher-Server/BasicPlatforms.json).

You can send Pull Requests relating to this file and other files, but there is HEAVY development going on at the moment, and your work may either be simple to implement or conflict with changes I'm making. Changes to this file like a new platform would be very much appreciated.

The Wiki page explaining how to set up a platform in BasicPlatforms.json will be up soon after the release of the update.

The Wiki page explaining how to collect information like what files and registry entries a program/platform edits can be found here: [Help code a platform](https://github.com/TcNobo/TcNo-Acc-Switcher/wiki/Help-code-a-platform). You can use this to help collect info to add other platforms to the BasicPlatforms.json file (As mentioned, if you do; please send PRs with your commits).

## Let's see some changes
Sure. For those not keeping up via the [Discord](https://discord.gg/bmPZVDjPX6), there is 1 new major feature besides the templated platforms.
**Game shortcuts.** Each platform will have a shortcut box where you can click games/programs to open them. These are automatically collected from your Start Menu folders if any exists - as defined in `BasicPlatforms.json`. Otherwise, you can add them by expanding the dropdown and clicking the `+`. This opens a folder you can drop `.lnk` and `.url` files - Normal windows "shell" shortcuts, and Steam/other platform shortcuts to games (These point to say `steam:\\` etc.)

This also means long-awaited support for Discord Canary, Discord PTB and other platforms is coming NOW if not very soon! You can help add platforms of your own, let me know about it and get it pushed in an update soon.

### Templated Platforms preview

![JWKgcA2ECE](https://user-images.githubusercontent.com/10319195/149788693-579e1c69-fd0d-4085-a674-4475a8a15fc9.gif)

### Game Shortcuts preview

![1AqN5WMnrl](https://user-images.githubusercontent.com/10319195/149788470-009e3861-6b8a-4858-8dab-5549b0564a2f.gif)

And that's all I can think of for now. ETA? No idea. I'm incredibly busy and have been working on nothing but this project for the past 8 days. If I need to update this post, I will with some extra info. Until then you can keep up with development on the [Discord](https://discord.gg/bmPZVDjPX6).

Thank you for your patience.
Wesley.

----
Issues tagged: #134 #133 #127 #125 #122 #121 #119 #118 #102 #101 #93 #82 
Issue tagged (Regards to game shortcuts): #131 #10 (Wow, it's been a while)
Issues tagged (Regarding platform requests - Will be left open until added): #90 #71 #54 
Issues that should be fixed alongside this update (Added to tag this post for more info): #116

**Comment by tired9494** [comment]
the discord link is invalid

**Comment by TcNobo** [comment]
> the discord link is invalid

And when I try to create a new one I see this 
![image](https://user-images.githubusercontent.com/10319195/151237087-6b7ae35f-1551-4108-9349-170336de4a0c.png)

I don't think the link is invalid, seems like something weird at Discord.
There is a download link on the Discord for this pre-release version with all the new features. Releasing there privately before GH just so people don't download it and expect something super smooth -- Even though it may be. Needs a test first.

**Comment by TcNobo** [comment]
Closing this for now as Version 5.0 is out and working well!
Thank you all for patience :)
