### ISSUE TITLE
Setings path

### ISSUE THREAD

**Issue by Makein** [TcNobo/TcNo-Acc-Switcher#136]
Wtf, where it save login info?
Reinstalled windows and all info gone!
Dawn, I installed this tool to backup my acc's...

**Comment by TcNobo** [comment]
This tool only swaps accounts. It does not store your account information.
This tool is used for swapping accounts by restarting platforms and changing "theLast logged in username". This way the 'switch' happens seamlessly and little-to-no sensitive information is stored. The platform in question manages the account.

This tool was not designed to back up accounts. If you own accounts and are able to sign into them on a fresh install, this tool is for you. It's not for backing up - or stealing accounts.

**Comment by Makein** [comment]
> 



> This tool only swaps accounts. It does not store your account information. This tool is used for swapping accounts by restarting platforms and changing "theLast logged in username". This way the 'switch' happens seamlessly and little-to-no sensitive information is stored. The platform in question manages the account.
> 
> This tool was not designed to back up accounts. If you own accounts and are able to sign into them on a fresh install, this tool is for you. It's not for backing up - or stealing accounts.

I not need stored account information or login\pass. 
I want it remember all settings that I add in it.
And if I would reinstall it again, next time I can reserve it and restore back.
So I would not show path to same launchers location.

**Comment by TcNobo** [comment]
Ah, ok. Thanks for clarifying.
A "backup settings" button is a useful idea, but I'm not sure how this would be done.

Some platforms save the last position/size of the window, as well as other settings on your computer and some online. Those that store info on your computer could be backed up, but wouldn't always work on a new computer -- Say login info is stored in that file: A new login = new file = new settings.

If you know the file location for any platforms it would be useful to test and create a feature like this :)

**Comment by TcNobo** [comment]
There is now a Backup and Restore button for platform settings in each platform's settings, as defined in the new `Platforms.json` file. See the file [here](https://github.com/TcNobo/TcNo-Acc-Switcher/blob/master/TcNo-Acc-Switcher-Server/Platforms.json).

Closing this issue for now. Feel free to reopen it if you experience any issues.
