### ISSUE TITLE
Switching Steam Accounts randomly

### ISSUE THREAD

**Issue by LEANderBoss** [TcNobo/TcNo-Acc-Switcher#137]
Hi, i discovered an issue were the account switcher switches steam account after restarting the pc. I had this two times.

**Comment by TcNobo** [comment]
There isn't a logical explanation I can think of other than a shortcut with a username attached to it that was used in the startup folder. The program doesn't have a mind of it's own lul

You can create shortcuts to switch accounts with the right-click context menu.

Check `C:\Users\<USERNAME>\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup` and click Properties on the `TcNo Account Switcher - Tray`, or similar shortcut. See if it ends with `+s:<numbers>...` in the Target text.
