### ISSUE TITLE
Installing WebView Runtime on every startup?

### ISSUE THREAD

**Issue by KresimirStojic** [TcNobo/TcNo-Acc-Switcher#138]
Is this supposed to run on every startup?
It seems not intentional...

One or more runtimes were not installed:
 + Microsoft WebView2 Runtime [~1,70 MB + ~120 MB while installing]
 = Total download size: ~122 MB

![Screenshot_14](https://user-images.githubusercontent.com/53954546/151327849-f15a9ce1-e289-486b-99cb-d58652756f45.png)
![Screenshot_15](https://user-images.githubusercontent.com/53954546/151327851-fd83d754-318c-4af9-8551-d35856d53c7e.png)

**Comment by TcNobo** [comment]
The check does run every startup... It's odd that it's not being detected, assuming it's installed?
Try opening the folder where it is installed and run `TcNo-Acc-Switcher_main.exe` to skip the check.
Does it work properly?

**Comment by H1ghIQQ** [comment]
Hello TcNo Thanks for your work on the program really helpful I have the same issue on windows 11 it says to install it but it is already installed and when the app is launched it shows an error message I linked 
![image](https://user-images.githubusercontent.com/98533169/151369327-b47e05bd-5e36-4888-9a1e-f8f3426c20f8.png)

**Comment by TcNobo** [comment]
I've never seen the last issue before... Though this does seem like a WebView2 Runtime issue. Try downloading the latest Evergreen installer, and if that doesn't fix it try downloading the fixed version for x64 here: https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section

**Comment by H1ghIQQ** [comment]
the evergreen installer also tells me I have it installed and the fixed version is a .cab file that I can extract but don't know what to do with it

**Comment by TcNobo** [comment]
Yikes I forgot about that one. No idea how to use the CAB.
Try uninstalling WebView2 from your PC, and downloading the Evergreen Standalone Installer then.
I'm releasing a newer version of the account switcher later tonight if all goes to plan so hopefully if you can't get it fixed, it should be fixed with everything updated.

**Comment by H1ghIQQ** [comment]
Thanks For Your Work and help

**Comment by KresimirStojic** [comment]
> The check does run every startup... It's odd that it's not being detected, assuming it's installed? Try opening the folder where it is installed and run `TcNo-Acc-Switcher_main.exe` to skip the check. Does it work properly?

Thanks! This seems to do it! Great work btw, its much better then anticipated!

**Comment by TcNobo** [comment]
Closing this for now. This should be improved.
Reopen this issue with a comment if you have further similar problems.

**Comment by EryX0** [comment]
this issue is fixed by opening the *_main.exe but still can't use my account shortcuts, any workarounds for that?
