### ISSUE TITLE
I dont know how to add account

### ISSUE THREAD

**Issue by jaeminkim-yeet** [TcNobo/TcNo-Acc-Switcher#14]
I tried different stuff

1. add new in TCNO (didn't work) and going back to the original

2. add my account in the big picture mode ( didn't work)

I do not know how to specifically add my new steam account in TCNO

**Comment by TcNobo** [comment]
After opening the account switcher:
1. Click the `Add New` button - Do not "sign out" via Steam, this will forget that accounts password.
2. Steam will restart, and ask you to input the user/pass. Enter the new details and make sure "Remember password" is checked.
After login completes, it should appear in TcNo Account Switcher's list on the next launch. You should be able to switch to and from this account.

For big picture mode, I have no idea but the process should be almost exactly the same. Sign into a new account, and make sure a Remember option is checked. You can then switch between accounts without needing to enter a password or 2-factor code.
