### ISSUE TITLE
League And steam issues

### ISSUE THREAD

**Issue by Zeralun** [TcNobo/TcNo-Acc-Switcher#140]
Hello ^^

my issue is in league of leagens is that every time i try to 
"Could not find logged in user" Then nothing happend 

when my friend trys to open the steam switsher the 
switcher opend the shoppage on hin and he is not closing steam 
when he close steam and try to log in another account it works 
the program is not able to close steam.

**Comment by Zeralun** [comment]
note: i installes league on a other space

**Comment by TcNobo** [comment]
Please see: https://github.com/TcNobo/TcNo-Acc-Switcher/issues/135
This should be fixed with the release coming out now :)
