### ISSUE TITLE
Issue with steam switcher

### ISSUE THREAD

**Issue by EDZX75** [TcNobo/TcNo-Acc-Switcher#143]
Idk why my steam cannot closing when i press login to any account can u help with this ? i have tried reinstal and nothing happen

**Comment by TcNobo** [comment]
Hi. Can you please provide a screen recording, screenshots or more details? I can't piece together what's happening.

**Comment by EDZX75** [comment]
When i press login the steam, on the 
bottom left it says closing steam and nothing happen

**Comment by TcNobo** [comment]
The only thing that's changed is you may be asked for admin to close/restart Steam now.

If that doesn't fix it, then for now try closing Steam manually from `Steam > Exit` (in Steam) or closing it through the Windows Task Manager.

I did change how closing works, so if there are lots of people having issues I'll make sure to look further into this.

Do make sure you're on the latest version by clicking the `?` -- It should be 2022-02-01_01

**Comment by EDZX75** [comment]
i have try it too, do you have any solution?

**Comment by EDZX75** [comment]
may i know the path data of tchno folder so i can try delete all files and try download again

**Comment by TcNobo** [comment]
Program files from the installer are default: `C:\Program Files\TcNo Account Switcher
User data files are in: `%AppData%\TcNo Account Switcher\` (Press Start+R and paste it in to travel here)

**Comment by EDZX75** [comment]
ok thx i will try it first then i gave the result

**Comment by EDZX75** [comment]
idk what happen to my steam it wont connect with my steam i think :(

**Comment by TcNobo** [comment]
Does it work with a previous version? 
The last version before major changes was v4.2: [2021-12-10_00](https://github.com/TcNobo/TcNo-Acc-Switcher/releases/tag/2021-12-10_00)

**Comment by EDZX75** [comment]
it work with previos version i think before the update yea and the steam wont connect like nothing happen when the tchno do something

**Comment by TcNobo** [comment]
Well... I haven't changed much other than how Steam is closed -- Try and install a previous version, like the one I mentioned and see if it's working. If it's not, it's something with Steam on your end, otherwise it may be something I changed... But I doubt, as it's working fine for me.

**Comment by EDZX75** [comment]
ok thx a lot bro i will try it

**Comment by TcNobo** [comment]
I have changed the method that's used by default to close Steam, and it should result in more reliable switching as before the update. Check `TcNo Account Switcher > Steam > Options` and try the following setting with different combinations if `TaskKill` is not working well. Restart the account switcher after changing this option.
![image](https://user-images.githubusercontent.com/10319195/152649255-d1ea483a-4754-48f4-b3d5-ab80a40cddc7.png)

Reopen and comment if you're still experiencing issues :)

**Comment by EDZX75** [comment]
Thx bro 👊 for the fix
