### ISSUE TITLE
Steam account switcher doesnt work properly

### ISSUE THREAD

**Issue by Michail77** [TcNobo/TcNo-Acc-Switcher#145]
Hi, 
like one hour ago I tried to log in to my second account as always trough account switcher shurtcut, but it logged me in my main account .. I tried this like 10x times and it kept logging me in to my main account and not my secondary .. I reseted cmos yesterday .. can this cause this issue ?? What should I do ? Thanks !!

**Comment by TcNobo** [comment]
When you're switching accounts does Steam close? This is usually the culprit.
It should be prompting you for admin when you swap accounts. If not, right-click the shortcut and run it as admin. This should fix the issue :)

**Comment by Michail77** [comment]
Yes, steam does close and open again and start logging in to the same account that it was logged before.
I have set opening with admin as default in properties.

**Comment by KilluaYT** [comment]
That error just appeared for me too. Dont know how to fix

**Comment by TcNobo** [comment]
@KilluaYT @Michail77 I will have a fix in a day or so. Let me know if installing an earlier version fixes it for you:
https://github.com/TcNobo/TcNo-Acc-Switcher/releases/tag/2021-12-10_00

**Comment by Michail77** [comment]
Yessss , I downloaded installer for version 4.2 and it wooorks !!!! Thanks for being So active, I love your program! Keep doing this Bro <3

**Comment by TcNobo** [comment]
:/ Alright that's a little annoying... I'll undo my changes for closing Steam  ~ Which will take a few minutes... But I do need to finish a half-baked feature I'm working on for now. Should be done by tomorrow this time - Hopefully.

**Comment by KilluaYT** [comment]
I downloaded 4.2, and didnt worked either (crashes on startup), but i deleted the one version i had before (300x) and launched the 4.2 updater and updated to 2022-02-01_01 and now it works

**Comment by TcNobo** [comment]
So... You uninstalled it... Then reinstalled an older version... Updated... And now it works fine? What? xD

**Comment by TcNobo** [comment]
I have changed the method that's used by default to close Steam, and it should result in more reliable switching as before the update. Check `TcNo Account Switcher > Steam > Options` and try the following setting with different combinations if `TaskKill` is not working well. Restart the account switcher after changing this option.
![image](https://user-images.githubusercontent.com/10319195/152649255-d1ea483a-4754-48f4-b3d5-ab80a40cddc7.png)

Reopen and comment if you're still experiencing issues :)
