### ISSUE TITLE
The ui not loading after launching 

### ISSUE THREAD

**Issue by eloelo42069** [TcNobo/TcNo-Acc-Switcher#146]
Basically when i click the steam icon to change steam accounts it prompts me for admin and when i click yes it gives me an error and the ui of the program isnt loading 
![image](https://user-images.githubusercontent.com/98883287/152141378-00b94577-0fae-49a4-8b6f-1cea9cb1d468.png)
![image](https://user-images.githubusercontent.com/98883287/152143258-b6b0f2e8-b39b-4cee-8444-4394ac12db48.png)
edit: it happens when i launch it with admin

**Comment by eloelo42069** [comment]
Translation Operacja została zwrócona ponieważ przekroczono limit czasu : 
The operation returned because it timed out

**Comment by TcNobo** [comment]
1. Press `Start+R`, and enter: `%AppData%\TcNo Account Switcher`.
2. Open `WindowSettings.json` with a text editor like Notepad.
3. Change the line that reads `"ActiveBrowser": "WebView",` to `"ActiveBrowser": "CEF",`, and restart the program.

It should then download CEF (A different browser) and use that for the program :)

**Comment by eloelo42069** [comment]
Sorry that you had to wait but it worked but i had to download the with CEF release to download it but its working.

**Comment by TcNobo** [comment]
Awesome. Glad you got it fixed ^
