### ISSUE TITLE
Error when clicking Steam switcher button

### ISSUE THREAD

**Issue by COMMANDERWONG** [TcNobo/TcNo-Acc-Switcher#148]
When I try to click the Steam switcher button on the main menu the following error message appears:
![image](https://user-images.githubusercontent.com/37576365/152179129-491a610d-d382-4d48-af0b-80209805afd5.png)
Clicking the button again sends me to the steam account page and the switcher works fine from then on.
Don't know what caused the issue.

**Comment by TcNobo** [comment]
Hit `Ctrl+Shift+I`, and go to the `Console` tab. Click the button again, and screenshot the red error block/s that show up in console.

**Comment by COMMANDERWONG** [comment]
![image](https://user-images.githubusercontent.com/37576365/152597468-69f80733-cb04-45d9-9584-77a54356fe5c.png)

**Comment by TcNobo** [comment]
Thanks for the clarification. I haven't thought of this possibility. Will patch it tomorrow.
Fix for now:
1. Open the Start Menu
2. Expand `Steam`, right-click any icon and click `More > Open File Location`

The reason this happened is a shortcut point to an icon that doesn't exist. So:
3. Find the shortcut with the missing icon, and simply delete it.

**Comment by TcNobo** [comment]
In fact, come to think of it... A game that's picked up has its shortcut copied into the account switcher's folder. Uninstalling the game will leave it there... TLDR Check for the broken shortcut in `%AppData%\TcNo Account Switcher\LoginCache\Steam\Shortcuts` as well -- This is more likely to be the culprit.

**Comment by COMMANDERWONG** [comment]
The broken shortcuts reappeared after I deleted them, any ideas?

**Comment by TcNobo** [comment]
[2022-02-05_00](https://github.com/TcNobo/TcNo-Acc-Switcher/releases/tag/2022-02-05_00) was released to try and fix this. If you have any further issues please reopen and comment :)
