### ISSUE TITLE
Origin as non admin cant stop interactive Helper Service

### ISSUE THREAD

**Issue by serossi** [TcNobo/TcNo-Acc-Switcher#149]
Current workaround, deactivate Origin Helper Service in Origin Settings.
Problem with workaround: has to be done at every new account

Second (better) Workaround, set Origin Helper service deactivated in Services so it never starts.
Resolves the issue also for new Accounts.

**Comment by TcNobo** [comment]
When you try to switch accounts the Origin Helper Service is not closing, right?
Does running the TcNo Account Switcher as admin help?

**Comment by serossi** [comment]
yes ofc that work

personally i deactivate helperservice anyway

**Comment by TcNobo** [comment]
The "Close method" option was added recently and should help solve this. Check `TcNo Account Switcher > Origin > Settings` and try different options. Combined should be the best, but you may get better results with just TaskKill or Close.
Let me know if things are better :)
![image](https://user-images.githubusercontent.com/10319195/152649198-cbac67c9-f918-4435-8adb-c8475f5e36e0.png)

**Comment by TcNobo** [comment]
Closing this issue as stale.
If you have anything to add, reply to this issue and I can reopen it.
