### ISSUE TITLE
Asking for PW sometimes

### ISSUE THREAD

**Issue by Nou4r** [TcNobo/TcNo-Acc-Switcher#15]
It works perfectly fine however after a few hours / days when i try to use a account i used a few accounts before the one im using right now, steam asks me for the pw which is super annoying, any idea how to prevent that or explanation?

**Comment by TcNobo** [comment]
The program does not interact with any passwords anywhere.
This is on Steam's part.
If you can restart your computer and Steam automatically logs you in, then you can use this software.

**Comment by Nou4r** [comment]
Any idea why steam sometimes asks to enter the pw again even tho it was 100% saved before?

**Comment by TcNobo** [comment]
No idea, but this entirely lies with Steam. Sometimes it remembers passwords, sometimes it doesn't.
The only thing I can think of is cache clearing software, or system cleanup software clearing Steam's login cache.
