### ISSUE TITLE
Failed to close steam again

### ISSUE THREAD

**Issue by COMMANDERWONG** [TcNobo/TcNo-Acc-Switcher#153]
![image](https://user-images.githubusercontent.com/37576365/152658570-295eb99a-fa64-45b7-9bf0-d9abcea356d6.png)
This error message appears in the newest version when I try to switch to another account.

**Comment by TcNobo** [comment]
I have changed the method that's used by default to close Steam, and it should result in more reliable switching as before the update. Check `TcNo Account Switcher > Steam > Options` and try the following setting with different combinations if `TaskKill` is not working well. Restart the account switcher after changing this option.
![image](https://user-images.githubusercontent.com/10319195/152649255-d1ea483a-4754-48f4-b3d5-ab80a40cddc7.png)

Let me know which works best for you, seems the one I chose as default has some issues...

**Comment by COMMANDERWONG** [comment]
![image](https://user-images.githubusercontent.com/37576365/152687035-52bdba02-cf4e-4f0f-b786-b0f30125d414.png)
Also, can I stop this by opening the switcher as admin everytime?

**Comment by COMMANDERWONG** [comment]
Also the "Best" option is the best for me

**Comment by TcNobo** [comment]
> ![image](https://user-images.githubusercontent.com/37576365/152687035-52bdba02-cf4e-4f0f-b786-b0f30125d414.png) Also, can I stop this by opening the switcher as admin everytime?

Yes, you can run it as an admin. I need to add an option to launch as admin by default ^

**Comment by COMMANDERWONG** [comment]
Thank you, everything's solved, I will close this issue now.
