### ISSUE TITLE
An error has occurred. This application may no longer respond until reloaded (Steam)

### ISSUE THREAD

**Issue by ItsAvNi** [TcNobo/TcNo-Acc-Switcher#156]
Hi, when i click on steam theres a message "An error has occurred. This application may no longer respond until reloaded"
how can i fix?

**Comment by TcNobo** [comment]
Press `Ctrl+Shift+I` and on the `Console` tab, screenshot it and post it here, or select and copy the entire red error message here.

**Comment by TcNobo** [comment]
I have fixed a few issues that were reported through the automatic crash reporter, you may have been one of them. Download the latest version and let me know if the problem persists: [2022-02-16](https://github.com/TcNobo/TcNo-Acc-Switcher/releases/tag/2022-02-16_00).

Comment on this issue/reply to this email if you still experience issues, or it hasn't improved.

**Comment by ItsAvNi** [comment]
Now working, thanks!
