### ISSUE TITLE
"Backup" crashes the app

### ISSUE THREAD

**Issue by 2x9Mon** [TcNobo/TcNo-Acc-Switcher#157]
as the title says. whenever I press "backup" or "backup all" in Steam - Settings tab of the app, it starts compressing files and then randomly crashes, leaving no zip archive behind. on the next launch, a crash log appears
[AccSwitcher-Crashlog-07-02-22_12-06-07.229.txt](https://github.com/TcNobo/TcNo-Acc-Switcher/files/8011232/AccSwitcher-Crashlog-07-02-22_12-06-07.229.txt)
.

**Comment by TcNobo** [comment]
Thanks will look into this. Seems it's not creating the folder structure: `C:\Users\mooni\AppData\Roaming\TcNo Account Switcher\Backups\BackupTemp\`. Should be a simple fix.

**Comment by TcNobo** [comment]
Try downloading the pre-release here, and let me know if things are fixed :)
https://github.com/TcNobo/TcNo-Acc-Switcher/releases/tag/2022-02-07_00

**Comment by TcNobo** [comment]
And the full release today 2022-02-10
https://github.com/TcNobo/TcNo-Acc-Switcher/releases/tag/2022-02-10_00
