### ISSUE TITLE
Ubisoft save only 1 account

### ISSUE THREAD

**Issue by Makein** [TcNobo/TcNo-Acc-Switcher#159]
When I add new one - it's overwrite existing one...
Help?

**Comment by TcNobo** [comment]
2022-02-05_00 (The latest update) seems to be working fine for me. I am able to freely switch between 2 or more accounts.
Does clicking New not let you log in to a new account? When switching it checks this file for an email: `C:\Program Files (x86)\Ubisoft\Ubisoft Game launcher\logs\launcher_log.txt` for a line with `User: `, and then following that is the username. If you Log Out using Ubisoft and not the account switcher, I assume it just adds to the file, and you'll have 2 account IDs there... The program takes the first occurrence by default currently.

Things you can try:
-  Try launching the account switcher as Admin, add your accounts and see if you can switch.
-  `TcNo Account Switcher > Ubisoft > Settings` and change the `[Advanced] Set method to close Ubisoft` option to another from the dropdown, to see if that helps. Maybe Ubisoft isn't closing properly when switching.

**Comment by Makein** [comment]
> 2022-02-05_00 (The latest update) seems to be working fine for me. I am able to freely switch between 2 or more accounts. Does clicking New not let you log in to a new account? When switching it checks this file for an email: `C:\Program Files (x86)\Ubisoft\Ubisoft Game launcher\logs\launcher_log.txt` for a line with `User: `, and then following that is the username. If you Log Out using Ubisoft and not the account switcher, I assume it just adds to the file, and you'll have 2 account IDs there... The program takes the first occurrence by default currently.
> 
> Things you can try:
> 
>     * Try launching the account switcher as Admin, add your accounts and see if you can switch.
> 
>     * `TcNo Account Switcher > Ubisoft > Settings` and change the `[Advanced] Set method to close Ubisoft` option to another from the dropdown, to see if that helps. Maybe Ubisoft isn't closing properly when switching.

I cleared cache and now it's working...
Was a bug, I guess.
Thanks

**Comment by TcNobo** [comment]
Can only assume that file wasn't being deleted for some reason. You can reopen this issue and comment again if you hit the same issue :)
