### ISSUE TITLE
Remember Online Status?

### ISSUE THREAD

**Issue by Nou4r** [TcNobo/TcNo-Acc-Switcher#16]
Everytime i switch accounts, my online status resets to the default one which is "Online" even if i had set it to invisible before. Is it possible to remember this somehow in the file since steam remembers it on its own?

**Comment by TcNobo** [comment]
I'm not too sure about starting "invisible". I will look into this for future versions when I find time :)

**Comment by TcNobo** [comment]
This feature has now been added to an upcoming release. There's TONS changing, as well as support for multiple platforms. This is one of the more useful things that is now included in the Steam switcher section.

![image](https://user-images.githubusercontent.com/10319195/113918935-4a02cd00-97e3-11eb-9b3e-b351f428bd83.png)

**Comment by TcNobo** [comment]
This has been implemented in the Public Beta.

You can get access to it through the [Discord: https://s.tcno.co/AccSwitcherDiscord](https://s.tcno.co/AccSwitcherDiscord)
(See #updates and #general-acc-switcher)
Let me know how your experience with the beta is. Need to find and work out some bugs I may have missed.

**Comment by Nou4r** [comment]
I'm very sorry for my late reply, awesome work on the Account Switcher so far just amazing. In this suggestion i meant if you could save the current state of the account or save if i clicked "login as invisible" so next time i double click the account it knows what to login as and have a default option for double click login, e.g. login invisible in all accounts.

**Comment by TcNobo** [comment]
As far as I understand, there's no way of getting the current state of an account, but if you log in as invisible, switch accounts and then swap back, Steam does remember the 'last state' and will most of the time login as that. I know people who have been invisible for 200+ days on Steam, and that's just closing/opening Steam as they start/stop their computers.
The same happens here when swapping accounts, at least for me.

Or you're asking for a 'global option' of "Login all accounts as default: Invisible"?

**Comment by TcNobo** [comment]
Added "Override" state for logging in through Steam. If users double-click, they can set a "default" for that in the settings screen. Right-Clicking and starting as a specific state remains unchanged.
This was added to code with commit 6ae75f83a8f09195863ce93e1ce6b4000f4ad6d0, and should be included in the next update.

![image](https://user-images.githubusercontent.com/10319195/134540856-58200b91-56df-4651-bb16-da4bee1a79dc.png)

**Comment by TcNobo** [comment]
Implemented. https://github.com/TcNobo/TcNo-Acc-Switcher/releases/tag/2021-09-28_00
