### ISSUE TITLE
Add option to not auto-start platform

### ISSUE THREAD

**Issue by StealthyDaud** [TcNobo/TcNo-Acc-Switcher#164]
This seems to be account specific so I'm not sure what causes it but on two of my accounts when I click the "+Add New" button the riot games client opens up and I log in but there is no option for League of Legends, just Valorant. Every other account works fine swell. Also (side question) is there a way that when I open my account it just boots up league rather than the riot client?

**Comment by TcNobo** [comment]
The program starts `C:\\Riot Games\\Riot Client\\RiotClientServices.exe`, so any games that are detected by the launcher should be there... Not too sure why it's not, but it's up to the Riot Launcher here. Not too much of an issue though I would say -- 

In the shortcuts section of the account switcher, do you have a League shortcut you can use at least?

**Comment by StealthyDaud** [comment]
Yeah that was my image, that's my bad for not using github and adding that
option to manually choose would be so sweet, thank you so much! your client
is amazing :)

**Comment by TcNobo** [comment]
There's now an option in the latest version, [2022-02-18_00](https://github.com/TcNobo/TcNo-Acc-Switcher/releases/tag/2022-02-18_00) to disable automatic starting platforms (Disable this setting that is on by default):

![image](https://user-images.githubusercontent.com/10319195/154698706-e0ed3e04-eb69-4201-a308-40fadc23e294.png)

Find this in `TcNo Account Switcher > Riot Games > Settings`.

Closing this issue as it should be a fix. While not exactly what you may have been hoping for, adding game shortcuts and turning off the auto-start feature should be all you're looking for :)

Re-open this issue with a comment if you have further input or problems.

**Comment by StealthyDaud** [comment]
Huh I don't seem to see the Automatically start Riot Games on account
switch. https://imgur.com/a/NMAQDCR

**Comment by TcNobo** [comment]
Click the `?` on any page to check the version. Make sure you're running version [2022-02-18_00](https://github.com/TcNobo/TcNo-Acc-Switcher/releases/tag/2022-02-18_00)
