### ISSUE TITLE
Adding Riot account seems buggy/ not working at all

### ISSUE THREAD

**Issue by Ku-Tadao** [TcNobo/TcNo-Acc-Switcher#165]
Heya,

When adding Riot accounts, I have noticed that it does work at first, but after adding one or two accounts, it seems to reset all the others and immediately throws me to the login screen, instead of logging in. 

if additional information is needed, feel free to make a request.

**Comment by TcNobo** [comment]
Yes, I am aware of this. Looks like I skipped including a `Cookies` folder. Should be fixed and more reliable in the next update likely tomorrow.

**Comment by TcNobo** [comment]
This should be fixed with the latest release [2022-02-16](https://github.com/TcNobo/TcNo-Acc-Switcher/releases/tag/2022-02-16_00).
Comment on this issue/reply to this email if you still experience issues, or it hasn't improved.
