### ISSUE TITLE
Some Errors I Found

### ISSUE THREAD

**Issue by Tharki-God** [TcNobo/TcNo-Acc-Switcher#167]
1. First:

 Riot Cookies Location have been changed from "C:\Users\Administrator\AppData\Local\Riot Games\Riot Client\Cookies\Cookies" to "C:\Users\Administrator\AppData\Local\Riot Games\Riot Client\Data\Cookies\Cookies". so Please change it.

2. Second

When I am am trying to Add Genshin to platforms, Its giving me errors. The error Logs are:
```
02/17/2022 08:03:14 (2022-02-16_01)	UNHANDLED CRASH: System.IO.DirectoryNotFoundException: C:\Users\TCNO\Documents\GitHub\TcNo-Acc-Switcher\TcNo-Acc-Switcher-Server\wwwroot\
   at TcNo_Acc_Switcher_Client.MainWindow.RunServer() in C:\Users\TCNO\Documents\GitHub\TcNo-Acc-Switcher\TcNo-Acc-Switcher-Client\MainWindow.xaml.cs:line 81
   at System.Threading.Thread.StartHelper.Callback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Thread.StartCallback()
```

and the code i added to platforms file is:
```
"Genshin Impact": {
      "Identifiers": [ "gi", "genshin", "genshinimpact" ],
      "ExeLocationDefault": "A:\MiHoYo\Genshin Impact\Genshin Impact game\GenshinImpact.exe",
      "ExesToEnd": [ "GenshinImpact.exe"],
      "PathListToClear": [ "SAME_AS_LOGIN_FILES" ],
      "LoginFiles": {
        "A:\\MiHoYo\\Genshin Impact\\Genshin Impact game\\GenshinImpact_Data\\webCaches\\Cookies": "webCaches\\Cookies",
        "A:\\MiHoYo\\Genshin Impact\\Genshin Impact game\\GenshinImpact_Data\\webCaches\\Cache\\index": "Cache\\index",
        "A:\\MiHoYo\\Genshin Impact\\Genshin Impact game\\GenshinImpact_Data\\webCaches\\Cache\\data_*": "Cache\\",
        "A:\\MiHoYo\\Genshin Impact\\Genshin Impact game\\GenshinImpact_Data\\webCaches\\Local Storage\\leveldb\\": "Local Storage\\leveldb\\",
		"A:\\MiHoYo\\Genshin Impact\\Genshin Impact game\\GenshinImpact_Data\\webCaches\\Code Cache\\js\\index-dir":"Code Cache\\js\\index-dir"
        "A:\\MiHoYo\\Genshin Impact\\Genshin Impact game\\GenshinImpact_Data\\webCaches\\GPUCache\\index": "GPUCache\\index",
        "A:\\MiHoYo\\Genshin Impact\\Genshin Impact game\\GenshinImpact_Data\\webCaches\\blob_storage": "blob_storage\\",
        "A:\\MiHoYo\\Genshin Impact\\Genshin Impact game\\GenshinImpact_Data\\TcNoAccSwitcher-ID.instance": "TcNoAccSwitcher-ID.instance"
      },
      "ExitBeforeInteract": true,
      "UniqueIdFile": "A:\\MiHoYo\\Genshin Impact\\Genshin Impact game\\GenshinImpact_Data\\TcNoAccSwitcher-ID.instance",
      "UniqueIdMethod": "CREATE_ID_FILE"
    }
```

What am I Doing wrong?

**Comment by TcNobo** [comment]
Thanks for the first, I'll have that updated today.
The error seems unrelated to the platform code, which looks good. I'll install Genshin in a bit to test it out myself. Good job with this ^. Will get to adding assuming it works.

The `%AppData%\TcNo Account Switcher\wwwroot` folder seems to not have been copied for you. Check if it is there, or not. It contains all the front-end files for the program, including images etc.
Go to the install folder (where the .exes are) and copy the `originalwwwroot` to ``%AppData%\TcNo Account Switcher\originalwwwroot`, then rename it to just `wwwroot`. This should restore functionality.

**Comment by Tharki-God** [comment]
> The `%AppData%\TcNo Account Switcher\wwwroot` folder seems to not have been copied for you. Check if it is there, or not. It contains all the front-end files for the program, including images etc. Go to the install folder (where the .exes are) and copy the `originalwwwroot` to `%AppData%\TcNo Account Switcher\originalwwwroot`, then rename it to just `wwwroot`. This should restore functionality.

Well, the Folder is here but the path your program is checking for is wrong, fix it. you have set the path to "C:\Users\Appdata\Roaming\TcNo Account Switcher\wwwroot".

**Comment by TcNobo** [comment]
I highly doubt that. Where do you see this value?
%AppData% is an environment variable so the username is automatically added, and expands to `C:\Users\<username>\AppData\Roaming`.

**Comment by Tharki-God** [comment]
> I highly doubt that. Where do you see this value? %AppData% is an environment variable so the username is automatically added, and expands to `C:\Users\<username>\AppData\Roaming`.
> 
> EDIT: On second look, the error doesn't point to anything to do with folders in the code (even though it does say `DirectoryNotFoundException`)... I can not figure out what is causing this. If you remove the platform you added, does it go back to normal? (Rename the `platforms.json` file to regenerate the original)

ik what is causing this and it is that check the first line of error it is 
`02/17/2022 08:09:24 (2022-02-16_01)	UNHANDLED CRASH: System.IO.DirectoryNotFoundException: C:\Users\TCNO\Documents\GitHub\TcNo-Acc-Switcher\TcNo-Acc-Switcher-Server\wwwroot\`
clearly saying here that its looking for TCNO folder under users and documents in it, you should change it to appdata. Sir you just messed up while writing it ig

**Comment by TcNobo** [comment]
Yeah, I see that, but I don't have it referenced ANYWHERE in my code:
![image](https://user-images.githubusercontent.com/10319195/154486121-d3caba2e-ee4d-440f-80ce-df86556be945.png)
as well as with an unescaped line here, only referenced for signing the .exes when I build them
![image](https://user-images.githubusercontent.com/10319195/154486454-26637e34-a7fa-4a7c-a5f5-30a4faf9ae36.png)


I see the error you're getting but I can't recreate this. It doesn't make sense to me at all.
The error, broken down is here:
- The client attempts to start the server using a saved port.
- If it fails, a new port for the server is generated and attempts to start.
- When it fails 10 times, it throws the last error generated by the server.
-> The last error generated by the server is that it can't find TCNO\Documents...\wwwroot.

I have no idea why it's looking for this folder when it's not referenced anywhere that I can find it. Over the 50k downloads and 500+ daily users you're the only one experiencing this, which is odd...

Back up the `Platforms.json` file you edited, delete the entire `%AppData%\TcNo Account Switcher` folder, as well as the folder it was installed to, and download a fresh copy. I can only think that either a folder is missing from the installed program files directory, or something else is afoot.

**Comment by Tharki-God** [comment]
nice

**Comment by Tharki-God** [comment]
let me reinstall it and update the issue

**Comment by Tharki-God** [comment]
yeah buddy as for your commit, the genhin folder would be "%Platform_Folder%\Genshin Impact game\GenshinImpact_Data\webCaches" not "%Platform_Folder%\GenshinImpact_Data\webCaches"

**Comment by TcNobo** [comment]
Yes, I'm launching the game directly, so it's not starting the launcher as they can be installed in 2 different places.

I haven't yet got a handler for exporting an entire key from the registry with all the subkeys, but doing it manually, yes, it seems everything required is in that registry folder.

With that being said the folder location isn't so important now if everything is in the registry, so I'll swap it out for the launcher exe now.

-----

**For a fix:**
- Try running the account switcher as Admin?

> Go to the install folder (where the .exes are) and copy the `originalwwwroot` to `%AppData%\TcNo Account Switcher\originalwwwroot`, then rename it to just `wwwroot`. This should restore functionality.

- Does doing this not help? Does the folder exist?

- If you hit `Ctrl+Shift+I` and go to the `Console` tab, is there error text? That would be a lot of help.

- Do earlier versions of the program work while the latest doesn't?

- And finally, you haven't moved the user data using the setting in-app, have you? I did a fresh install on a Windows 11 and Windows 10 virtual machine where I can't get the same issue...

**Comment by TcNobo** [comment]
Awesome, good to know it's the same for you. I assumed that `h1158948810` was different for everyone, and hence copying the entire registry key with all its subkeys would be better.

**Comment by Tharki-God** [comment]
> Awesome, good to know it's the same for you. I assumed that `h1158948810` was different for everyone, and hence copying the entire registry key with all its subkeys would be better.
> 
> I do hope we can figure out what the issue with it not launching is...

well did you installed the whole game like from the launcher?

**Comment by Tharki-God** [comment]
> **For a fix:**
> 
> * Try running the account switcher as Admin?
> 
> > Go to the install folder (where the .exes are) and copy the `originalwwwroot` to `%AppData%\TcNo Account Switcher\originalwwwroot`, then rename it to just `wwwroot`. This should restore functionality.
> 
> * Does doing this not help? Does the folder exist?
> * If you hit `Ctrl+Shift+I` and go to the `Console` tab, is there error text? That would be a lot of help.
> * Do earlier versions of the program work while the latest doesn't?
> * And finally, you haven't moved the user data using the setting in-app, have you? I did a fresh install on a Windows 11 and Windows 10 virtual machine where I can't get the same issue...

Am already an admin, and did try it manually too, the folder exists and I did it nothing changed.
and there is nothing in the console in developer mode, already tried it before, didn't use earlier versions yet. and no I haven't changed user data in-app.

**Comment by TcNobo** [comment]
Very odd... The exception it's throwing says the error, and then the place where the error is being thrown manually, rather than the actual error location itself. I need to quickly improve how the error is handled to get more accurate information of what's going on here... Give me a few.

**Comment by Tharki-God** [comment]
> Very odd... The exception it's throwing says the error, and then the place where the error is being thrown manually, rather than the actual error location itself. I need to quickly improve how the error is handled to get more accurate information of what's going on here... Give me a few.

funny

**Comment by Tharki-God** [comment]
![image](https://user-images.githubusercontent.com/73281112/154501949-4a1dec24-1f54-42ca-9cd9-b01253d4cbe3.png)
This is the actual error am getting, and when i set it to developer, it gives me the error in log file

**Comment by TcNobo** [comment]
Never mind, I was able to recreate this issue exactly.
1. Pause the program right before the server is started, [here](https://github.com/TcNobo/TcNo-Acc-Switcher/blob/master/TcNo-Acc-Switcher-Server/Program.cs#L43)
2. Delete or rename the `%AppData%\TcNo Account Switcher\wwwroot` folder to make it inaccessible.
3. `System.IO.DirectoryNotFoundException: 'C:\Users\TCNO\AppData\Roaming\TcNo Account Switcher\wwwroot\'` is thrown, as you have, and this is the part of the code that shows as an error: [here](https://github.com/TcNobo/TcNo-Acc-Switcher/blob/master/TcNo-Acc-Switcher-Server/Startup.cs#L90-L94)

The working directory is being set to `Globals.UserDataFolder`, which is in my case: `C:\Users\TCNO\AppData\Roaming\TcNo Account Switcher\`. Why yours is set to this makes no sense.

This is defined in code [here](https://github.com/TcNobo/TcNo-Acc-Switcher/blob/master/TcNo-Acc-Switcher-Globals/Globals.cs#L49-L76).
If your install folder (where `TcNo-Acc-Switcher.exe` is) contains `userdata_path.txt` it will use the path inside (By default this file does not exist), or, it uses `%AppData%\\TcNo Account Switcher`.

----

If you do not have this file in your install folder, then I'm completely clueless as to why it's looking for this folder as it's not hardcoded anywhere.

**Comment by Tharki-God** [comment]
![image](https://user-images.githubusercontent.com/73281112/154507486-ed551bd5-e081-4178-97fd-f84e32336d28.png)
there is no file like tha here

**Comment by TcNobo** [comment]
The only place I can find it referenced with the distributed program is in the first line of `TcNo-Acc-Switcher-Server.staticwebassets.runtime.json`, which is generated on the build. Why it isn't being programmatically set on your computer I have no idea...

The program runs fine with that file deleted. Try delete it and run the program to see if you get a different result.

**Comment by Tharki-God** [comment]
![image](https://user-images.githubusercontent.com/73281112/154514123-08da33bb-add7-4109-b557-3b4c09ff3990.png)
still this
