### ISSUE TITLE
New Accs dont show up

### ISSUE THREAD

**Issue by Nou4r** [TcNobo/TcNo-Acc-Switcher#17]
When i click "Add new" and then login with an account and remember password option the tool doesn't find it, i have to restart my pc in order for it to find it for some reason, any idea why this might be happening?

**Comment by TcNobo** [comment]
The program works off the `Steam\config\loginusers.vdf` file. If Steam hasn't updated this file with your new account, it won't appear within the program.
You're not adding a new account in the account switcher, but rather adding it to a list of previously logged-in accounts with Steam.
The account switcher reads the login file on startup, so a restart of just the account switcher should be enough.

**Comment by TcNobo** [comment]
Assuming this is fixed.
