### ISSUE TITLE
Steam Null Reference Exception

### ISSUE THREAD

**Issue by biehla** [TcNobo/TcNo-Acc-Switcher#170]
Hi!

I've been trying to set up this tool for switching my steam accounts. I keep getting this "error has occurred" popup when I click on the steam button in the main menu.

![image](https://user-images.githubusercontent.com/36610944/154864316-d03e45ec-50df-4fc2-9b6b-d07b7ca020c5.png)

When I open the console, I get this:

![image](https://user-images.githubusercontent.com/36610944/154864388-c5fb94d1-c672-477a-94bf-c9844edf23f2.png)

Steps I have taken so far:
  - Deleting the TcNo folder in appdata to reset the app
  - Manually reinstalling all the prereqs
  - Updating to the newest version
  - Checking my steam `loginusers.vdf` for invalid formatting and characters

**Comment by TcNobo** [comment]
An incredible example of a detailed, useful issue. Thank you.

The part that it's breaking on is trying to escape username text. I assume one of the usernames in `loginusers.vdf` is blank?
I can easily re-create and fix this issue if I had a copy of your `loginusers.vdf`.
Join the [Discord](https://s.tcno.co/AccSwitcherDiscord) and let me know there when you join. I'm TechNobo#1337.
Add me, and personal message me your `C:\Program Files (x86)\Steam\config\loginusers.vdf` file.

I can drop this into my PC, and recreate the issue, hopefully.

This file won't give me anything more than usernames and SteamIDs of your accounts. I can't gain access to anything.

**Comment by biehla** [comment]
Sounds good, thanks! I've dropped you a message in the #tech-support channel.

The usernames in the file look good to me (no blanks or characters that usually need to be escaped.

**Comment by TcNobo** [comment]
Solved through Discord.
Essentially the program is looking for case-specific parts of the `loginusers.vdf` file, and yours are capitalized differently. `TimeStamp` is what you had where the program looks for `Timestamp`.
This should be fixed with the next update.
