### ISSUE TITLE
Login data missing after update.

### ISSUE THREAD

**Issue by UnknownWitcher** [TcNobo/TcNo-Acc-Switcher#171]
I am/was using the  zip version, I clicked the notification within the software to update and now all my login data is gone.

[EDIT]
I have found the login data within the LoginCache folder but it doesn't show up in the app.

**Comment by UnknownWitcher** [comment]
Found the issue, for some reason the folder for **Epic Games** was named "**Epic**" which is why the data couldn't be found. I haven't tested other platforms since I don't have multiple accounts on those platforms.

![image](https://user-images.githubusercontent.com/82295355/155199535-f56bcdda-ffb4-410f-8400-48776dae1604.png)

**Comment by TcNobo** [comment]
Yes, you must have updated from a few versions ago.
There were major changes to how platforms work, so more can be added easily. Renaming platforms was one of them.
