### ISSUE TITLE
[Suggestion] Add option for Default Platform

### ISSUE THREAD

**Issue by seanbperiod** [TcNobo/TcNo-Acc-Switcher#173]
Love the new update with being able to customize which platforms show 👍

As someone who only uses this for 1 Platform, I'd like the option to either:

1. Set a default Platform to open when TCNO opens, so that I can immediately select an account to switch to 
2. Have TCNO automatically open Platform to account switcher if no other Platforms have been configured

Keep up the great work!

**Comment by TcNobo** [comment]
Sounds like a good idea. I'll have to add some text letting the user know on the `Manage extra platforms` page.
For now, you can right-click any platform and make a desktop shortcut for it, to achieve the same thing.

**Comment by TcNobo** [comment]
This feature was added and will be available in the next update later today. https://github.com/TcNobo/TcNo-Acc-Switcher/commit/7301b70beaffef0d393d632bea8a8850b2619f8d
