### ISSUE TITLE
[BUG] Cannot swap accounts with steam shortcut created in desktop

### ISSUE THREAD

**Issue by suhasholla** [TcNobo/TcNo-Acc-Switcher#177]
Steps to reproduce: 
1. Start from clean install
2. Add your steam accounts
3. Create steam desktop shortcut within settings after clicking on Steam, goto settings and check mark Steam Switcher Desktop shortcut
4. Open steam switcher by clicking on newly created Desktop shortcut
5. Try to open/swap any account, it fails to load/open steam .

**Comment by TcNobo** [comment]
Simple bug. Changing the case of the shortcut argument fixes it. From `steam` to `Steam`. I'll work on a patch for this.

Example:
`"C:\Program Files\TcNo Account Switcher\TcNo-Acc-Switcher.exe" steam`
to
`"C:\Program Files\TcNo Account Switcher\TcNo-Acc-Switcher.exe" Steam`

**Comment by TcNobo** [comment]
A fix should be included in the next update, likely tomorrow :)

**Comment by suhasholla** [comment]
> A fix should be included in the next update, likely tomorrow :)

Waiting for the update with the fix.

**Comment by TcNobo** [comment]
Yes, I've been super busy and unable to push an update. I'll have one out within a few hours.
