### ISSUE TITLE
Offline Mode

### ISSUE THREAD

**Issue by revilationer** [TcNobo/TcNo-Acc-Switcher#18]
If you can add the feature that which we selected account start in offline mode it would be great

**Comment by emersonjr** [comment]
agreed!

**Comment by TcNobo** [comment]
This is a planned feature. I'm quite sure it's possible.

**Comment by TcNobo** [comment]
Duplicate of #16

**Comment by TcNobo** [comment]
This feature is confirmed and is coming in the next release of TcNo Account Switcher. See the above comment for a link to the issue with the information on this topic.
