### ISSUE TITLE
Broken Add New Button

### ISSUE THREAD

**Issue by DabMK** [TcNobo/TcNo-Acc-Switcher#185]
The "Add New" button does not work with Epic Games. The path is right

EDIT: The "LOGIN" button is also broken. The notification with "Starting EpicGames..." appears, but it never runs

 - OS: [Windows 10 21H2]
 - Version: [v5.0 - 2022-02-22_00]

**Comment by TcNobo** [comment]
Is this just with the Add New button, or switching accounts too?

- General launch issue fixes:
Does running the account switcher as admin help?
Switch accounts using the account switcher. Does launching Epic Games manually have the new accounts on it?
Head into `TcNo Account Switcher > Epic Games > Settings` and try changing the option `Set method to start Epic Games`

**Comment by DabMK** [comment]
Yes, it is just with Login and Add New button, switching account works well. Running the program as admin does not fix the bug and accounts switches well

**Comment by TcNobo** [comment]
Unfortunately I can't recreate this issue.
Let's try doing this manually to see if it does work (This is what the program does to switch accounts):
1. Close Epic Games completely. Make sure that it's closed using the Task Manager.
2. Press `Start+R` and enter `%LocalAppData%\EpicGamesLauncher\Saved\Config\Windows\`
3. Delete `GameUserSettings.ini`.
4. Press `Start+R` and enter `regedit`
5. Navigate into `HKEY_CURRENT_USER\Software\Epic Games\Unreal Engine\Identifiers` and delete `AccountId`.

The next time you start Epic Games it should ask you to login.

If this manual workaround works, then... I'm not too sure. If this doesn't work, Epic may have changed the way they store info - Which wouldn't make much sense...
If this does work, then likely it's something to do with the TcNo Account Switcher and file/folder permissions on your computer, as it works for me.
