### ISSUE TITLE
Safety concerns

### ISSUE THREAD

**Issue by ArslanDoesDev** [TcNobo/TcNo-Acc-Switcher#186]
Hello there! So far, I am loving this app. I've always been a huge paranoid though, so I was wondering: are our so called "tokens" being stored on a server or something like that? Are they stored locally? Do they get sent anywhere?

Best Regards, 
Arslan.

**Comment by TcNobo** [comment]
Everything that is collected is stored in `%AppData%\TcNo Account Switcher`.
Nothing is set to a cloud. The only "talking" this does to a website of mine is checking the version for updates, and updating.
Only a small few platforms collect files with "tokens", and they are stored in `%AppData%\TcNo Account Switcher\LoginCache`
