### ISSUE TITLE
Is not working anymore

### ISSUE THREAD

**Issue by o0Julia0o** [TcNobo/TcNo-Acc-Switcher#187]
it worked for month, but now the password is beeing asked for every start.

**Comment by TcNobo** [comment]
This needs more details.
What platform is not working as expected?

**Comment by mattladon** [comment]
They're right. Every time I try to log into steam it requires the password for every account.

**Comment by TcNobo** [comment]
The Steam account switcher is by far the most stable in the TcNo Account Switcher. It uses a widely-spread method of just swapping out usernames. I just tested it now and can confirm it still works on Windows 11 for Steam and Steam Beta, as well as Windows 10.

Check the Wiki for [Steam - I need to enter a password every time I switch](https://github.com/TcNobo/TcNo-Acc-Switcher/wiki/FAQ---More-Info#i-need-to-enter-a-password-every-time-i-switch---steam). This should help.
I can't assume what platform OP was having issues with, however, and may still be useful.

**Comment by TcNobo** [comment]
There is an issue affecting a few users where the files aren't being edited properly when switching, specifically `loginusers.vdf`. If this is happening to you, you should see a popup error notification when switching accounts - If you haven't already found a solution https://github.com/TcNobo/TcNo-Acc-Switcher/releases/tag/2022-03-29_00
