### ISSUE TITLE
Crash on startup after update

### ISSUE THREAD

**Issue by DogeeDev** [TcNobo/TcNo-Acc-Switcher#192]
Here's what the event log says

First:
Faulting application name: TcNo-Acc-Switcher_main.exe, version: 4.0.0.0, time stamp: 0x61e1d8d9
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1566, time stamp: 0x0833f2d4
Exception code: 0xe0434352
Fault offset: 0x0000000000034f69
Faulting process id: 0x3f04
Faulting application start time: 0x01d83965ab480427
Faulting application path: C:\Program Files\TcNo Switcher\TcNo-Acc-Switcher_main.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 654eff30-acd0-4a2e-b8f8-ec7cfd82b84a
Faulting package full name: 

Second:
Faulting package-relative application ID: 
Application: TcNo-Acc-Switcher_main.exe
CoreCLR Version: 6.0.121.56705
.NET Version: 6.0.1
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileLoadException: Could not load file or assembly 'PresentationFramework, Version=6.0.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'PresentationFramework, Version=6.0.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

**Comment by DogeeDev** [comment]
reinstalling net 6.0.1 didn't help

**Comment by DogeeDev** [comment]
Server version works

**Comment by TcNobo** [comment]
Unfortunately, no idea what's causing this... I recently moved to Windows 11, so I can only assume it's that.
I need to remember how to add a reference to this now :/

**Comment by TcNobo** [comment]
Found out what it is: https://github.com/dotnet/core/issues/7172, https://github.com/dotnet/winforms/issues/6663
I think I need to retarget for another version, users may have to update .NET... Looking into it...

**Comment by DogeeDev** [comment]
installing .NET Desktop Runtime 6.0.3 & ASP.NET Core Runtime 6.0.3 fixed the issue

**Comment by DogeeDev** [comment]
> Found out what it is: [dotnet/core#7172](https://github.com/dotnet/core/issues/7172), [dotnet/winforms#6663](https://github.com/dotnet/winforms/issues/6663) I think I need to retarget for another version, users may have to update .NET... Looking into it...

thx :)

**Comment by TcNobo** [comment]
Patch released 2022-03-16_01 (Forces users to download 6.0.3) https://github.com/TcNobo/TcNo-Acc-Switcher/releases/tag/2022-03-16_01
