### ISSUE TITLE
[Feature Request] Symlinks

### ISSUE THREAD

**Issue by pwall2222** [TcNobo/TcNo-Acc-Switcher#195]
NTFS has supported symlinks for a while now and they could be used for cutting time when switching accounts because you don't have to copy every file to the new directory's. It can be implemented in very smart ways like nvm for windows. It could be opt in so in the case that the user uninstalls the program it doesn't delete their accounts by default.

**Comment by TcNobo** [comment]
There isn't a use for this just yet as files are a few KB to very low MB - if that. With bigger files, this would make sense.
That being said, it may not help between reinstalls (likely). De-authenticating accounts, etc. That being said, if you have an account saved it should currently try and copy files if you were to uninstall and reinstall the platform anyway. (Switch to an account and the files will be copied in, even if it's a fresh install).

**Comment by TcNobo** [comment]
I think this is a good idea when it comes to thousands of files or large files that need to be swapped out. At the moment it wouldn't add anything but complexity, and more things that could break. I'll leave this as an idea, but I'll close it for now until there is a use for symlinks.
