### ISSUE TITLE
Stopped Working

### ISSUE THREAD

**Issue by jocasrb** [TcNobo/TcNo-Acc-Switcher#2]
After 2-3 days of using your software, for some reason its not working well anymore. When app is launched I only get this, like a toolbar only, cant choose any account:
https://i.gyazo.com/a0bf5afd54f68c922b566482aa7a200b.png

How to fix this?

**Comment by TcNobo** [comment]
Another user had this issue and reported it on the Discord (https://discordapp.com/channels/217649733915770880/653291673811550218/689888606747492455)
Invite: https://discord.gg/hy5acv

The program saves the window's size. For some reason, it was made super short.
Try grabbing the bottom or a corner and stretching it out as you would any program.
You can also edit `settings.json` with any text editor. Change the numbers next to `WindowSize` to be what you want. Anything bigger than what it is now will let you stretch it if you can't.
`X, Y`
Let me know if this fixes your issue.
