### ISSUE TITLE
 One or more prerequisite is not installed : Microsoft WebView2 Runtime

### ISSUE THREAD

**Issue by suhasholla** [TcNobo/TcNo-Acc-Switcher#201]
On windows 11, when I try to open the application it says

![image](https://user-images.githubusercontent.com/3531083/161382839-476a3fd7-2f9a-4284-a359-139bdfbd0814.png)

when I already have the required version

![image](https://user-images.githubusercontent.com/3531083/161382815-dc81b919-85a4-4bb1-8d67-4917fc089958.png)

Currently on 

![image](https://user-images.githubusercontent.com/3531083/161382895-9e73b9d0-f495-424f-a7bd-351642ddb4c6.png)

I have tried multiple times downloading and installing. it doesn't recognize the web view installed
I even tried to manually open the app it throws an error

**Comment by TcNobo** [comment]
I'm not sure why this is happening to you and one other user, as far as I know. I'm also on Win 11 and not experiencing this, or in any of my test environments.
For now, create a shortcut to `TcNo-Acc-Switcher_main.exe` instead of `TcNo-Acc-Switcher.exe` to skip the launch check.

**Comment by suhasholla** [comment]
> I'm not sure why this is happening to you and one other user, as far as I know. I'm also on Win 11 and not experiencing this, or in any of my test environments. For now, create a shortcut to `TcNo-Acc-Switcher_main.exe` instead of `TcNo-Acc-Switcher.exe` to skip the launch check.

Thanks for the quick reply, I had tried that, I am getting error
![image](https://user-images.githubusercontent.com/3531083/161385200-51365a64-ccee-4b36-ada2-c5bcef77ff0e.png)

I am using the zip version, I tried installing through exe application but no luck
Have you checked in the windows 11 build, may be it is happening in this W11 build 593

**Comment by suhasholla** [comment]
Fixed by installing the latest version of Microsoft Edge WebView2 from https://developer.microsoft.com/en-us/microsoft-edge/webview2/
