### ISSUE TITLE
Can't switch account

### ISSUE THREAD

**Issue by DevJonas01** [TcNobo/TcNo-Acc-Switcher#202]
![image](https://user-images.githubusercontent.com/69815018/162646660-1bd553a4-f0e3-4098-ba85-ad49db447110.png)

Everytime I try to switch an account this shows up, I
 tried all of the different kill modes for steam. It only works when, I close steam manually.

**Comment by TcNobo** [comment]
Does running the account switcher as admin help? Is Steam running as admin?
