### ISSUE TITLE
[Enhancement] Add Sony PS Remote Play support (`setting.cache` file swapping)

### ISSUE THREAD

**Issue by akemin-dayo** [TcNobo/TcNo-Acc-Switcher#205]
If you have any interest in adding account switching support for Sony's PS Remote Play client on Windows, account switching can be quite easily achieved by simply swapping out the `%localappdata%¥Sony Corporation¥PS Remote Play¥setting.cache` file.

**※ NOTE:** This file _does_ also contain client configuration data, so settings like framerate limit and data collection preference will be swapped along with the PSN ID authentication token.

For reference, my existing solution for PS Remote Play account swapping is just a custom shell script that I wrote to swap out the `setting.cache` files for me, which has remained working across several app updates now.

---

Unrelated to this issue, but if anyone reading this is wondering if you can easily switch accounts on macOS…
* Use `defaults read com.playstation.RemotePlay RefreshToken` to get the current auth token for your session
* … and use `defaults write com.playstation.RemotePlay RefreshToken "AUTH_TOKEN_HERE"` to set one you've saved.

---

(Also, wow I'm about… 2 years late to the news that TcNo now apparently supports more than just switching Steam accounts, since I was stuck using a version from 2020 this whole time ;P)

**Comment by TcNobo** [comment]
> I was stuck using a version from 2020 this whole time

If it works, no need to fix it :)
New versions come with unforeseen issues, of course, and new platforms.

I'll add this platform s soon as I can. I don't have any PS accounts, but as long as I don't need to pay, I can test.

**Comment by TcNobo** [comment]
Forgot to close this, but it was implemented in [2022-04-29_00](https://github.com/TcNobo/TcNo-Acc-Switcher/releases/tag/2022-04-29_00)
