### ISSUE TITLE
Suggestion: isolating battle.net "additional command line argument" option

### ISSUE THREAD

**Issue by superarts** [TcNobo/TcNo-Acc-Switcher#209]
Not sure where this setting is saved, but I observed that once it's changed for my account 1, my account 2's setting has been changed as well. Would you consider make it account specific please?

PS: I came here searching for a working D2R multiboxing solution, great job!

**Comment by TcNobo** [comment]
I'm not too sure what you mean? Do you have more details?
So far the program works as follows ([Code](https://github.com/TcNobo/TcNo-Acc-Switcher/blob/master/TcNo-Acc-Switcher-Server/Pages/BattleNet/BattleNetSwitcherFuncs.cs#L198-L271)):
- Kills Battle.Net.
- Reads accounts from `%AppData%\Battle.net\Battle.net.config`
- It the looks for `"SavedAccountNames": "x@gmail.com,y@hotmail.com"` etc.
- Removes, and re-add the account's email to be the first item on the list.
- Saves the above file
- Launches BattleNet ([Code](https://github.com/TcNobo/TcNo-Acc-Switcher/blob/master/TcNo-Acc-Switcher-Server/Pages/BattleNet/BattleNetSwitcherFuncs.cs#L266)) -- I think this is what you're interested in?

The program doesn't go out of it's way to mess with configs for anything else, unfortunately. They would need to be explicitly included in the process to keep settings, etc... But I don't know what file it's stored in (and if it's a unique file like the `1234.xml` files in the above folder - how to get those filenames). Game specific especially.

**Comment by superarts** [comment]
I see, the config I mentioned must be something very specific. Closing as it's out of the scope of tcno switcher

**Comment by TcNobo** [comment]
If it's game-specific it's out of scope. If it's platform-specific as in BattleNet then it should be included here.
