### ISSUE TITLE
Add New button for steam restarts steam into the same account

### ISSUE THREAD

**Issue by Kaizen5000** [TcNobo/TcNo-Acc-Switcher#211]
Clicking Add New to try and add a new steam account restarts steam but doesn't present me with the login prompt, instead, it logs in with the account I've just logged into. Not being able to add an account this way means I can't properly switch accounts using the app.

1. Log into steam with Account Switcher open
2. Enter my steam guard code into steam
3. Click on Add New. Steam will then restart into the same account

I have 2 steam accounts, one with steam guard, one without. I've tried cleaning all the times in the advanced clean, clicking each of the clean buttons and retrying to log in. The only way for me to get back to the log in screen is to log out, which as you know, means the app won't switch properly.

**Comment by TcNobo** [comment]
I can not recreate this with the version I'm working on. The next update should be released in a day or so, let me know if you still have the issue then. I will comment again here when that is live.
