### ISSUE TITLE
Kill steam when exiting a game

### ISSUE THREAD

**Issue by emanuelelupini** [TcNobo/TcNo-Acc-Switcher#212]
Is there a command line for this? I need it because I use a frontend and I want to use steam when necessary only

thanks

**Comment by TcNobo** [comment]
Currently it just launches programs with shortcuts, it doesn't track how long you use them.

Are you looking for a button to kill Steam?
In the meanwhile use `Taskkill /f /im steam`

**Comment by TcNobo** [comment]
I've been thinking about this for a while. A lot of shortcuts lead to launchers that close after the game is launched, or other processes are started from them. Keeping track of games running and then closing Steam when they close (could think launcher/anticheat popup or anything closing is the game closing) would be very difficult, to say the least.

I do think this is a good suggestion, though after looking further into it, it does seem difficult to pull off for games with open/close something before they launch -- Which are a lot of games...

I'll close this for now but you or anyone else can chime in with ideas if you have any.
