### ISSUE TITLE
AccSwitcher can't open steam/epicgames

### ISSUE THREAD

**Issue by criskkky** [TcNobo/TcNo-Acc-Switcher#213]
**Describe the bug**
I recently formatted my computer and the application stopped working properly, the problem is that it doesn't open steam or epic games, do you think I missed installing a driver?

**To Reproduce**
Normal use, nothing special.

**Expected behavior**
Start apps normally

**Desktop (please complete the following information):**
 - OS: Win 10 Pro 21H2

**Additional context**
PC recently formatted

**Comment by TcNobo** [comment]
I assume you mean from the shortcut popup at the bottom of the window?
Do you get any kind of error? Hit `Ctrl+Shift+I`, and try again.

Maybe the shortcut links are broken but were carried over from a previous install. Open `%AppData%\TcNo Account Switcher\LoginCache\Steam\Shortcuts` (For Steam, for example), and see if the shortcuts work. You can right-click and check Properties for them as well to see if something odd happened.

Worst comes to worst, just clear the folder and re-add your shortcuts so they start working again.

**Comment by criskkky** [comment]
![image](https://user-images.githubusercontent.com/36176343/170635915-5ade55b3-2610-4f57-b0e6-7522e6f39ae8.png)

I found this, idk if that could help to solve the problem,
To clarify my problem: Account-Switcher only can kill apps, but can't open them (i just run a clean install)

btw i checked "%AppData%\TcNo Account Switcher\LoginCache\Steam\Shortcuts" and everything seems to be ok.

**Comment by TcNobo** [comment]
Does it open Steam/Epic when switching accounts? Just the shortcuts that don't work?

**Comment by criskkky** [comment]
It doesn't open Steam/Epic when switching accounts, i installed epic and steam in default folders.

**Comment by criskkky** [comment]
Fixed, idk how, but now it works, if i found the error i will tell u, thanks 4 supp! <3
