### ISSUE TITLE
Steam guard code needed, when switching

### ISSUE THREAD

**Issue by Jona-Walpert** [TcNobo/TcNo-Acc-Switcher#215]
I need to type in my steam guard code, everytime I switch my account. Is there a way to avoid that?

**Comment by TcNobo** [comment]
This is an issue with Steam on your computer, unfortunately.

This program swaps out the "Last logged in user" text, and Steam manages the rest. Whether Steam 'remembers' or 'forgets' your password/Steam Auth code entirely rests with Steam on your computer.

As long as you're not using "Change User" or "Sign Out" in Steam on your computer, there shouldn't be any issues.

While there are other users who have previously experienced this, it's either with a few accounts, or goes away on it's own.
