### ISSUE TITLE
Tcno not launching correctly.

### ISSUE THREAD

**Issue by Demo337** [TcNobo/TcNo-Acc-Switcher#217]
the problem is when I need to run Tcno it never launched what ever happen, but I found out that the "TcNo-Acc-Switcher.exe" it never launch the application but when I run the "TcNo-Acc-Switcher_main.exe" it launched, this lead to me in every time I need to run the account switcher I need to run the "TcNo-Acc-Switcher_main.exe" to launch the application, in addition I already updating the  .NET 6.0.4, I hope you found solution for this.
thanks for your effort.

**Comment by TcNobo** [comment]
Hi, thanks for the info.
Unfortunately, I can't do much with this little info. For 99.9% of users it works flawlessly, but I do want to fix little edge cases like this... I'll leave this open for a while, but there's nothing I can do at the moment.

Are you running anything out of the normal? Any specific AntiVirus or operating system optimizations, etc?

**Comment by Demo337** [comment]
> Hi, thanks for the info. Unfortunately, I can't do much with this little info. For 99.9% of users it works flawlessly, but I do want to fix little edge cases like this... I'll leave this open for a while, but there's nothing I can do at the moment.
> 
> Are you running anything out of the normal? Any specific AntiVirus or operating system optimizations, etc?

after deep search I found the file manager application That I used cause the problem for some reason, after I uninstall it, the Tcno app work flawlessly, thank you for your effort 👍
