### ISSUE TITLE
Failed to load steamui.dll

### ISSUE THREAD

**Issue by Wh3reThefuck** [TcNobo/TcNo-Acc-Switcher#219]
**Describe the bug**
When I try to log in to my steam account through the switcher, I get an error with the text "Failed to load steamui.dll". When i launch steam manually, it's start without any errors

**To Reproduce**
1. Start program
2. Click on 'steam' icon
3. Click on account

**Expected behavior**
already obvious.

**Screenshots**
![изображение](https://user-images.githubusercontent.com/92229688/174412196-0b97f7b1-a663-474c-b300-77a4d6b7949e.png)

**Desktop (please complete the following information):**
 - OS: Win 11 21H2

**Comment by Wh3reThefuck** [comment]
So... Restarting the program solves everything

**Comment by TcNobo** [comment]
This is good. No idea why this could have popped up but I'm glad you fixed it.

**Comment by deleniti** [comment]
This happened to me too on the latest version. Restarting also fixed the problem for me
