### ISSUE TITLE
Flagged as malicious by 3 engines in Virustotal

### ISSUE THREAD

**Issue by osisic** [TcNobo/TcNo-Acc-Switcher#22]
Hi Wesley,

Please check it on virus total. I used the 64-bit Installer file "TcNo.Account.Switcher.-.Installer.x64.exe" and it got flagged by 3 scanners.

https://www.virustotal.com/gui/file/b55cbc8f6ae16711ff95caa1ff6f83fa1afce52a52295e737864fc3af6a39aab/details

Kind Regards.

**Comment by TcNobo** [comment]
[I don't intend to be rude, but I'll be straightforward]
The installer is NSIS, https://nsis.sourceforge.io/ - No idea what could be causing issues with "SecureAge APEX", "Bkav Pro" and "Cynet". I've personally never heard of these antivirus programs.
As for my account switcher itself: I coded it from scratch. The entire source is available online, including the installer build script for the aforementioned NSIS.

If you do not trust the installer; don't use it. The program is portable, and the .zip versions work just fine [when extracted to a folder].
If you wanted, you could build the program and installer using the publically available source code.

A quick google for "W32.AIDetect.malware1" takes me to this Reddit post: https://www.reddit.com/r/antivirus/comments/fy16b8/w32aldetectvmmalware/

As mentioned by EndangeredPootis: 
> Its only detected by one, never heard of before AV, use logic, if it was malware it would be detected by many more, particulary major ones such as Bitdefender, Kaspersky etc, not some unknown, probably bad antivirus, I have seen so many people like you post things like this im im getting so goddamn annoyed.

~~ Although, I'm not annoyed :)
The only reason I can see the installer being detected is: Yes, it "drops" files on the user's disk. Viruses can do that too. However, Correlation does not imply causation.
