### ISSUE TITLE
When ever I use switcher to switch between accounts my epic games can't connect with internet.

### ISSUE THREAD

**Issue by LesterLikee** [TcNobo/TcNo-Acc-Switcher#222]
**Describe the bug**
When ever I use switcher to switch between accounts my epic games can't connect with internet it keeps on loading and please wait  and after that error comes MD-DL this 

**To Reproduce**

**Expected behavior**

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Win 10 21H1

**Additional context**
I have to put this line inside a file and it fix my problem

Line 

[Launcher]
ForceNonSslCdn=false

I have to put this inside the `C:\Program Files (x86)\Epic Games\Launcher\Engine\Config\Windows\WindowsEngine.ini `

and when I switch account this removes and I have to face the same issue

**Comment by TcNobo** [comment]
I haven't received this issue before, and can't recreate it, unfortunately.
Having issues with Epic Games' SSL CDNs sounds like a network/Windows issue. This software doesn't change anything that could cause this as far as I understand.
I'm not too sure how to solve this, as it isn't really a bug with my software as far as I can tell - other than adding some help to the TcNo Account Switcher - Epic Games Wiki page.

Does logging out and in normally cause this issue - without the temporary fix in the ini file?

**Comment by LesterLikee** [comment]
nope

**Comment by TcNobo** [comment]
For now, I think creating info on a Wiki page here for it is the best solution. I don't think it's right to automatically insert this line for everyone, which is the only other solution I can think of at the moment.

**Comment by TcNobo** [comment]
Alright, I'll close this issue for now. I've included some info on our Wiki page, [here](https://github.com/TcNobo/TcNo-Acc-Switcher/wiki/Common-errors#su-md-hsh-failed-to-asynchronously-deserialize-a-manifest)
