### ISSUE TITLE
Crashing after some time

### ISSUE THREAD

**Issue by LDzik** [TcNobo/TcNo-Acc-Switcher#23]
So its just crashing even when i reinstalled TcNo and .NET Core but nothing helps
Here is my crash log:
07.04.2021 15:27:11	UNHANDLED CRASH: System.ComponentModel.Win32Exception (2): Nie można odnaleźć określonego pliku.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at TCNO_Acc_Switcher_CSharp_WPF.MainWindow.closeSteam()
   at TCNO_Acc_Switcher_CSharp_WPF.MainWindow.LoginSelected()
   at TCNO_Acc_Switcher_CSharp_WPF.MainWindow.LoginMouseDown(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at TCNO_Acc_Switcher_CSharp_WPF.App.Main()

**Comment by TcNobo** [comment]
After clicking Login, the program is unable to start Steam again.
The error is "The specified file could not be found.".
Make sure that the correct Steam directory is selected, and that the account switcher is running as Admin.

Go to the TcNo Account Switcher install directory, example: `C:\Program Files\TcNo Account Switcher\Steam`
Open `SteamSettings.json` with Notepad.
Check if the path next to: `"SteamFolder"` is valid, and has `steam.exe` in it. In my case it shows as `"C:\\Program Files (x86)\\Steam\\"`

If steam.exe IS found in that directory, and it is accessible, please send the location of the file here. I can only think it has something to do with language differences.

**Comment by LDzik** [comment]
I changed to valid path but now im getting this error:

04/07/2021 16:02:03	UNHANDLED CRASH: System.ComponentModel.Win32Exception (0x80004005): Nie można odnaleźć określonego pliku
   w System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   w TcNo_Acc_Switcher_Steam.MainWindow.CloseSteam() w C:\Users\TechNobo\Documents\GitHub\TCNO-Acc-Switcher\TcNo-Account-Switcher\TcNo-Acc-Switcher_Steam\MainWindow.xaml.cs:wiersz 616
   w TcNo_Acc_Switcher_Steam.MainWindow.SwapSteamAccounts(Boolean loginNone, String steamid, String accName) w C:\Users\TechNobo\Documents\GitHub\TCNO-Acc-Switcher\TcNo-Account-Switcher\TcNo-Acc-Switcher_Steam\MainWindow.xaml.cs:wiersz 757
   w TcNo_Acc_Switcher_Steam.MainWindow.LoginSelected() w C:\Users\TechNobo\Documents\GitHub\TCNO-Acc-Switcher\TcNo-Account-Switcher\TcNo-Acc-Switcher_Steam\MainWindow.xaml.cs:wiersz 737
   w System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   w System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   w System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   w System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   w System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   w System.Windows.Input.InputManager.ProcessStagingArea()
   w System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   w System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   w System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   w System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   w System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   w MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   w MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   w System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   w System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   w System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   w MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   w MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   w System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   w System.Windows.Application.RunDispatcher(Object ignore)
   w System.Windows.Application.RunInternal(Window window)
   w TcNo_Acc_Switcher_Steam.App.Main()

**Comment by TcNobo** [comment]
Same error code. Would you mind copy/pasting the "SteamFolder" and path next to it in another comment?

**Comment by LDzik** [comment]
This is my steam folder and it have steam.exe
"SteamFolder":"C:\\Program Files (x86)\\Steam\\"

**Comment by LDzik** [comment]
I have path with double \ 
`"SteamFolder":"C:\\Program Files (x86)\\Steam\\"`

**Comment by LDzik** [comment]
It only happens when i try to login or add account

**Comment by TcNobo** [comment]
Ah ok, it seems to be having issues closing Steam... https://github.com/TcNobo/TcNo-Acc-Switcher/blob/master/TcNo-Account-Switcher/TcNo-Acc-Switcher_Steam/MainWindow.xaml.cs#L546

1. Can you close Steam completely first (using Steam > Exit, or right-clicking it in your start bar > Exit) and switching accounts? Does that work?
2. Are you able to use Command Prompt (Press Windows+R, type in CMD and hit Enter) - Do you see the Command Prompt window?

**Comment by LDzik** [comment]
1. it doesnt work
2. Sure i can use cmd

**Comment by TcNobo** [comment]
If you click the `?` on the main menu, are you on version `3002`?

**Comment by LDzik** [comment]
Yes im on version 3002

**Comment by TcNobo** [comment]
OK so from what I've found; it seems to be having permission/authentication issues with Windows. For some reason, it can't access the folder. Maybe it was installed on another user account? Or is somehow limited by software?

exception 0x80004005: https://stackoverflow.com/a/31739227/5165437 , https://techcommunity.microsoft.com/t5/office-365-networking/system-component-model-win32exception-0x80004005/m-p/1160271
Either that or this file just doesn't exist in the programs eyes... 
![image](https://user-images.githubusercontent.com/10319195/113886302-dbad1300-97c0-11eb-9b1b-c9d5063dfc1e.png)

**Comment by LDzik** [comment]
![obraz](https://user-images.githubusercontent.com/63643405/113886665-27f85300-97c1-11eb-9b8c-54e7f7c5aaf4.png)

**Comment by TcNobo** [comment]
Ok... I'm thinking it has something to do with language?
Try entering the folder as it appears in the screenshot above, where `Program Files` shows up differently?
I doubt this would actually make a difference, but worth a shot.

**Comment by LDzik** [comment]
no its just visual thing
![obraz](https://user-images.githubusercontent.com/63643405/113887041-6f7edf00-97c1-11eb-8c0c-e2d9a0d5ce09.png)

**Comment by LDzik** [comment]
Ok i will just wait for the new update, becaouse this happend to me after updating from verion 2 to 3

**Comment by TcNobo** [comment]
The Open Beta is now live. Please do try it out and let me know if you have success :)

You can get access to it through the [Discord: https://s.tcno.co/AccSwitcherDiscord](https://s.tcno.co/AccSwitcherDiscord)
(See #updates and #general-acc-switcher)
Let me know how your experience with the beta is. Need to find and work out some bugs I may have missed.

**Comment by LDzik** [comment]
uh So a bit late reply but when I try to launch it says that I don't have installed .NET version 5.0.0 even when I have it installed. I tried reinstalling .NET, fixing it but nothing works
![obraz](https://user-images.githubusercontent.com/63643405/119695458-7a173580-be4e-11eb-9b35-9d26cdf4651d.png)

**Comment by TcNobo** [comment]
Responded to you in Discord as well.
Make sure you have all 3 (three) requirements installed:
**WebView2 Runtime**: <https://go.microsoft.com/fwlink/p/?LinkId=2124703>
**Microsoft .NET 5 Desktop Runtime** AND: **ASP.NET Core 5.0 Runtime**: <https://dotnet.microsoft.com/download/dotnet/5.0/runtime>
^ Note you download 2 from the last site. See the image below for reference

**Comment by LDzik** [comment]
ok I will close the ticket for now because everything is working perfectly (and let's hope it stays this way)
