### ISSUE TITLE
TCNO won't open 

### ISSUE THREAD

**Issue by RootyBruh** [TcNobo/TcNo-Acc-Switcher#245]
It just doesn't open and idk what to do..... ( things that i've done are: reinstall microsoft edge, reinstall webviewer, reinstall tcno, reinstall all the requirements )

**Comment by TcNobo** [comment]
As long as all the requirements are installed, a few things:
- Have you installed/used the software before on this installation of Windows? Is this your first time trying to use it?
- Can you provide more details? After double clicking do you see nothing? Does the window flash open, or remain blank or a solid color?
- Are you running anything that could be interfering with it? Strong AV/drive protection software/settings, or anything out of the ordinary?

**Comment by Evo-c** [comment]
@RootyBruh  In the install folder run **TcNo-Acc-Switcher_main.exe** and it should work, it launches when using that file but if I run normally it instantly closes with no logs.

**Comment by RootyBruh** [comment]
> As long as all the requirements are installed, a few things:
> 
> * Have you installed/used the software before on this installation of Windows? Is this your first time trying to use it?
> * Can you provide more details? After double clicking do you see nothing? Does the window flash open, or remain blank or a solid color?
> * Are you running anything that could be interfering with it? Strong AV/drive protection software/settings, or anything out of the ordinary?

I have used it before but i was stupid enough to delete a folder called "microsoft" which i think is the cause and i realized later on what that folder had.... ( i'm talking about webview ) and after that it did not turn on again.... it said install webview 2 and i installed it but still nothing i just click the app to open and nothing happens, no console, no flash open, nothing happens and it's as if i haven't opened it

**Comment by RootyBruh** [comment]
> @RootyBruh In the install folder run **TcNo-Acc-Switcher_main.exe** and it should work, it launches when using that file but if I run normally it instantly closes with no logs.

tried that but still nothing

**Comment by RootyBruh** [comment]
sorry for my bad english too
