### ISSUE TITLE
Crash after opening

### ISSUE THREAD

**Issue by Jonybtw** [TcNobo/TcNo-Acc-Switcher#249]
Already tried cleaning the "AppData\Roaming\TcNo Account Switcher" folder but after I restart it the same error appears, tried to reinstall the required runtimes and it's the same, please help never had problems with it before.

![TcNo-Acc-Switcher_main_8A4jlYDz1B](https://user-images.githubusercontent.com/84144569/183531365-8944095c-eedd-4a43-a4f4-8da7abed6d3f.png)

**Comment by TcNobo** [comment]
Yes, sorry. I'm not sure if this is an issue with the most up-to-date versions, I do remember fixing this at a stage.
It's crashing when trying to speak to https://tcno.co, my website -- to check for updates.
The website is completely down as I'm migrating to another back-end. Should be a few more hours.
Sorry.

**Comment by Jonybtw** [comment]
Thanks for replying back fast, I have the latest version uploaded, yes I noticed that the error is about trying to connect through the protocol, is there any way to disable updates for now?

**Comment by TcNobo** [comment]
Unfortunately not that I remember adding. Thought I had patched this completely :/

**Comment by pavvj** [comment]
I am also getting this issue.

**Comment by TcNobo** [comment]
I am aware. I'm working as fast as I can.

**Comment by fazftw** [comment]
appreciate your work!

**Comment by TcNobo** [comment]
Functionality should be restored.
One thing. Maybe chrome is annoying, but is [https://tcno.co/](https://tcno.co/) secure for you?

![chrome_HulbM59sdg](https://user-images.githubusercontent.com/10319195/183542350-bb77dd4d-5751-42ce-97c7-2ea4d0359c98.png)

**Comment by Jonybtw** [comment]
> Functionality should be restored. One thing. Maybe chrome is annoying, but is https://tcno.co/ secure for you?
> 
> ![chrome_HulbM59sdg](https://user-images.githubusercontent.com/10319195/183542350-bb77dd4d-5751-42ce-97c7-2ea4d0359c98.png)

Safe in Firefox.

**Comment by Jonybtw** [comment]
> I've tried disabling the protocol it doesn't let me because I think it only allows you to when the program is fully loaded here: ![TcNo-Acc-Switcher_main_aaahGKf2dW](https://user-images.githubusercontent.com/84144569/183535263-7c49bb85-16ac-4c6d-8ced-6ce4e18bb3b5.png)

Hi the error is gone but could you fix this above?

**Comment by TcNobo** [comment]
@Jonybtw hit `Ctrl+Shift+I`,  and screenshot the red error text in the `Console` tab, so I can look at it.
The `tcno:\\` protocol is for switching accounts via the command line. In other words `Command Prompt > tcno:\\s:<steamid>`.

For a temporary fix: Run the program as admin and check/uncheck the checkbox again.
It adds itself to the Registry, and hence could have a permission error leading to the error. A restart of the program should be good enough.

**Comment by Jonybtw** [comment]
I've tried opening as admin before but now somehow it worked, anyways here is the error:
![msedgewebview2_jZqO8Tb32V](https://user-images.githubusercontent.com/84144569/183549589-893fbf82-89fc-4c49-8de4-456ad1d2a1fc.png)

**Comment by TcNobo** [comment]
Alright, thanks. Will look into patching this for the next release.
