### ISSUE TITLE
When try to install for the first time have issues with first time runner

### ISSUE THREAD

**Issue by Stalker-hash** [TcNobo/TcNo-Acc-Switcher#257]
![Screenshot 2022-09-21 081732](https://user-images.githubusercontent.com/59626436/191419752-d9fe709d-5267-4412-937d-3ad7cddd4872.png)

**Comment by TcNobo** [comment]
Running as admin should work, otherwise manually create the folder `C:\Users\Excal1bur\Desktop\New folder\runtime_installers\`.
Likely a permissions issue. Running as admin should help.
