### ISSUE TITLE
Error on application launch

### ISSUE THREAD

**Issue by mohammed-alaa** [TcNobo/TcNo-Acc-Switcher#258]
**Describe the bug**
Installed the application using the installer. This error shows up every time I launch the application.

**To Reproduce**
This error shows up every time I launch the application.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/30788249/191503521-2b180794-5ad7-42ca-a641-1d00357f0d17.png)
![image](https://user-images.githubusercontent.com/30788249/191507567-f04f49de-da2e-4a1c-8147-af30ce7c603e.png)

**Desktop (please complete the following information):**
 - OS: Win 11 Pro 21H2

**Additional context**

**Comment by mohammed-alaa** [comment]
> Had someone with the same issue on Discord the other day. It was a firewall issue. "Simplewall" or Malwarebytes was blocking access to the site even though they were disabled.
> 
> If you can access https://tcno.co, and more specifically https://tcno.co/Projects/AccSwitcher/api/stats/. The second link should show `Cannot GET /sw/Projects/AccSwitcher/api/stats/`
> 
> The website seems to be running fine, so it may be a firewall issue as well. Odd that this is now the second report.

- I do not have either of the mentioned applications installed.
- I cannot access either links, as shown in the screenshot below.

![image](https://user-images.githubusercontent.com/30788249/191576730-d5428946-484a-4090-89e4-7c802bc6c62f.png)

**Comment by TcNobo** [comment]
Very odd... My website and host don't seem to have issues. I have everything running through Cloudflare. Where are you located? Maybe I can use a VPN to see if I can replicate issues

**Comment by mohammed-alaa** [comment]
I tried accessing the above links using a VPN and it worked successfully.
I am from Egypt.

**Comment by TcNobo** [comment]
Good to hear that it worked. I'll close the issue and look further into it.

**Comment by xld5** [comment]
i have the same problem can anyone help me
