### ISSUE TITLE
steam.exe not found

### ISSUE THREAD

**Issue by nawafkhalidd** [TcNobo/TcNo-Acc-Switcher#259]
**Describe the bug**

**To Reproduce**

**Expected behavior**
A clear and concise description of what you expected to happen, if not already obvious.

**Screenshots**
If an error bar shows at the bottom of the window, press `Ctrl+Shift+I` and go to the `Console` tab where you'll likely find an error. Screenshot this and attach it here. You are free to blank out personal info (if any, but this is unlikely)

**Desktop (please complete the following information):**
 - OS: [e.g. Win 10 21H1]

**Additional context**

**Comment by TcNobo** [comment]
Steam is not installed to the normal location of `C:\Program Files (x86)\Steam`.
Navigate to where you have it installed, and select Steam.exe. 
Click `C:` with the folder icon to navigate to the folder, or copy and paste/type it in manually
![image](https://user-images.githubusercontent.com/10319195/193428252-847909cd-463e-4b6c-adb4-a61bdf192151.png)
