### ISSUE TITLE
steam.exe not found and cant log in into any steam account 

### ISSUE THREAD

**Issue by Mileslov** [TcNobo/TcNo-Acc-Switcher#260]
**Describe the bug**
steam.exe not found and cant log in into any steam account 
![Screenshot (2)](https://user-images.githubusercontent.com/114823634/193418406-5987fdfb-f2ed-4dd0-9826-2b91900df6dd.png)

PLEASE FIX IT

**Comment by TcNobo** [comment]
Steam is not installed to the normal location of `C:\Program Files (x86)\Steam`.
Navigate to where you have it installed, and select Steam.exe. 
Click `C:` with the folder icon to navigate to the folder, or copy and paste/type it in manually
![image](https://user-images.githubusercontent.com/10319195/193428252-847909cd-463e-4b6c-adb4-a61bdf192151.png)

**Comment by Mileslov** [comment]
That helped thanks!
