### ISSUE TITLE
Backup/restore steam accounts isnt working for me

### ISSUE THREAD

**Issue by asm00009** [TcNobo/TcNo-Acc-Switcher#266]
Hi

I have done a back up of the steam accs and then when I restore on other computer the accs dont show on the menu

**Comment by TcNobo** [comment]
The account switcher does not store user login details, it only swaps out tokens already validated with your computer, or a username in a file (literally just text) - And the platforms handle the rest. It is not possible to 'copy' accounts between computers using this program, and is intended to work this way as it's a lot safer.

You can't port accounts between computers, it's just for reinstalling the account switcher.
