### ISSUE TITLE
Import account from csv,txt,json...

### ISSUE THREAD

**Issue by ninhpn1337** [TcNobo/TcNo-Acc-Switcher#281]
Hi No-Acc-Switcher developt
Please can you make the import accounts from files like csv,txt,json... please. 
thank you so much!

**Comment by TcNobo** [comment]
Not possible. This account switcher merely saves usernames, and swaps them out in the platforms' files. Like changing the text "Steve" to "Bob", and restarting Steam. Steam handles auth and the rest.

This app does not save, or ask for account passwords.
