### ISSUE TITLE
Issue with beta Version: 2021-06-02_01

### ISSUE THREAD

**Issue by K9Paradox** [TcNobo/TcNo-Acc-Switcher#31]
When clicking on Login nothing happens, cannot log into any account using the switcher. I reset settings, and still not working sadly.

**Comment by TcNobo** [comment]
Yes, if you're talking about Steam - I'm working on a fix now :)

**Comment by K9Paradox** [comment]
All good, yes Steam, probably should have mentioned that. Thanks for the amazing application!

**Comment by TcNobo** [comment]
Should be fixed in 2021-06-02_02 (Updated just now). https://github.com/TcNobo/TcNo-Acc-Switcher/commit/b5afa6a2360efa9f26aa6623994ad1f939b60cbd
Let me know if the issue is fixed.

**Comment by TcNobo** [comment]
Closing, assuming it's fixed.
