### ISSUE TITLE
Tray_Users.json

### ISSUE THREAD

**Issue by deprale** [TcNobo/TcNo-Acc-Switcher#35]
https://i.imgur.com/0z149ll.png -> Error
Cause: right click on the tray app, or simply close it so it goes into tray mode.

**Comment by TcNobo** [comment]
Whoops! This was a leftover from testing.
The latest update should have this fixed. https://github.com/TcNobo/TcNo-Acc-Switcher/commit/5bd3e763e036c7753240c499e3824b5b057256be

**Comment by TcNobo** [comment]
Assuming this was fixed. Closing.
