### ISSUE TITLE
Crash on Startup After Settings Change

### ISSUE THREAD

**Issue by hvchiman** [TcNobo/TcNo-Acc-Switcher#38]
Installed using the installation tool. It launched after installation and worked fine. I changed a few settings and the program crashed. Any time I try to open the program now, it will open for a second and crash.

**Comment by TcNobo** [comment]
I assume you're the same person who commented something along these lines in the Discord?
Was it the "Low ram usage" and "exit to tray" options? You can reset settings in `Documents\TcNo Account Switcher`. More than likely just deleting the WindowSettings.json file will reset the settings that broke the account switcher.

Let me know what settings do break it so I can look into it - If not what I mentioned above :)

**Comment by TcNobo** [comment]
This should be fixed in the latest update 2021-06-26_00.
Either: Download and install a new copy, or
Delete `Documents\TcNo Account Switcher\WindowSettings.json`, start the program and update.
