### ISSUE TITLE
Error Message 

### ISSUE THREAD

**Issue by Khalid** [TcNobo/TcNo-Acc-Switcher#39]
After installing the required runtime etc. I tried opening the steam account switcher and I kept on getting this error message. "An error has occurred. This application may no longer respond until reloaded. Reload. ![](https://i.imgur.com/xCFHRkq.png)

Went to the valorant tab and it says. "Duplicate install. More than 1 Valorant install found."  ![](https://i.imgur.com/l6UhiMP.png)

Other than that everything works.

**Comment by TcNobo** [comment]
Please get the error again, then hit `Ctrl+Shift+I` to open the developer window.
Go to the Console tab.
Take a screenshot of the red error text and post it here, please :)

**Comment by Khalid** [comment]
![image](https://user-images.githubusercontent.com/29549755/123496733-3a509300-d632-11eb-85e7-5026e67a212b.png)

**Comment by TcNobo** [comment]
This looks very similar to other issues some people were mentioning. I assume you're running the latest version (2021-06-23_01) which you can check with the `?` in the bottom right of the program.

It has something to do with the `loginusers.vdf` file in your `Program Files(?)\Steam\config` directory. Something in the file is likely corrupt or malformed. Some users who used the older 'Steam only' version of my software had this issue where random `"`s popped up everywhere, spacing was thrown off (not that this has any effect other than visual).

The latest version tries to look at (if available) `loginusers.vdf_last` as well, which in some cases does not have all weird issues...

The simplest issue is deleting that file, which will make Steam 'forget' what accounts you've previously logged into, logging into your first account with "Remember Password" on and then logging into your other accounts using the 'Add New' button on the account switcher. It's the simplest way to make the file look and work properly again. Manual labour can be done as well editing it in notepad instead, correcting issues.... Though for non-programmers it may be difficult to spot the issue - such as a random `"` inside 2 more quotation marks containing a name, for example.

You can also join the community Discord, and send a message. I'll add you so you can personal message me, and send me that `loginusers.vdf` file from your `Steam\config` folder so I can have a look at it and probably fix it up / see what's wrong with it.

**Comment by Khalid** [comment]
Alright yeah i'll try to fix it. What about the riot games issue.  "Duplicate install"

**Comment by TcNobo** [comment]
Yes, you have previously installed it to a second location (unless my code is off...).
See `%ProgramData%\Riot Games\RiotClientInstalls.json` and verify that VALORANT does not show up twice.
The program uses the first to appear on the list.

See my RiotClientInstalls.json as an example:
```
    "associated_client": {
        "E:/Games/Riot Games/League of Legends/": "E:/Games/Riot Games/Riot Client/RiotClientServices.exe",
        "E:/Games/Riot Games/LoR/live/Game/": "E:/Games/Riot Games/Riot Client/RiotClientServices.exe",
        "E:/Games/Riot Games/VALORANT/live/": "E:/Games/Riot Games/Riot Client/RiotClientServices.exe",
        "H:/temp/VALORANT/live/": "E:/Games/Riot Games/Riot Client/RiotClientServices.exe"
    },
```

**Comment by Khalid** [comment]
Yeah fixed it. Thanks much love!
