### ISSUE TITLE
Any chance on Linux support?

### ISSUE THREAD

**Issue by LunixWasTaken** [TcNobo/TcNo-Acc-Switcher#40]
This seems like an extremly useful tool, worked pretty good on my Windows instance.

Considering i am mainly a Linux user, i would have hoped this could support Linux or Compiled using Linux and dotnet.

Either i don't have the required understanding of what's missing or there is just simply no chance it won't run on linux (Maybe it will after this request)

Thanks ahead!

**Comment by TcNobo** [comment]
There is a very good chance this can run on Linux in the future, that's the nice part of .NET 5. The 'server' is the part that does all the work swapping files and registry changes. That runs on Blazor, a mixture of web front-end code and C# as the backend using ASP.NET.

The 'Client' won't run on Linux, as it uses WebView2. it's just a simple window with a browser inside of it that automatically connects to the server, and displays content from there. If you open the server itself and go to the link in a browser; you can use the program as normal.

The program has some parts inside of it already marked as 'windows only' - parts that mess with the registry, as the compiler throws up warnings if they're not marked... but it should be easy enough to add Linux versions of functions that can swap out files and the rest.

Most of the code for the front-end and styles etc can stay almost exactly the same. Not much needs to change other than how the actual swapping of accounts works, and probably the way that they are collected to be displayed as well... Somewhat.

I personally have very little experience in Linux, so it's not something I'll be developing at all currently, especially with most things having to be run through something like Wine anyways (?). While this is not something that won't happen, it's not something I can make happen at this point. It is something the Linux community interested in the project can help with, however.

All it needs is:
- A front-end 'webview' type window to connect to the server automatically, and hopefully some hooks (probably not the right word) like the existing ones to move the window around via the HTML window borer at the top, resizing etc.
- Backend changes to some of the functional code that handles how accounts are collected and swapped around.

**Comment by RoyvEmpel** [comment]
I would also really like to see this become a thing :)

**Comment by zihaaad** [comment]
is there any similar project for linux steam?

**Comment by zihaaad** [comment]
okay. I found [this](https://github.com/coldfix/steam-acolyte) for linux

**Comment by RoyvEmpel** [comment]
> okay. I found [this](https://github.com/coldfix/steam-acolyte) for linux

Amazing! Thanks :D
