### ISSUE TITLE
[BUG] Changing between accounts on different regions on Riot Games

### ISSUE THREAD

**Issue by Achime11** [TcNobo/TcNo-Acc-Switcher#41]
If I try to change into an account with a different region on Riot Games, the launcher asks me again for the credentials.
When I tried to change between accounts in the same region its work perfectly.

**Comment by TcNobo** [comment]
I would think this is an issue with different files being edited that I haven't looked into yet, as I only have EU accounts.
I'll look into this.

**Comment by TcNobo** [comment]
Fixed in the latest commit https://github.com/TcNobo/TcNo-Acc-Switcher/commit/015c438bf28593bfe91cfe10546fd87ec321f179
Will be pushed with the next update soon.

**Comment by TcNobo** [comment]
Update released. Do let me know if you have any other issues, and if this issue still persists.
Thanks for your help improving the program.
https://github.com/TcNobo/TcNo-Acc-Switcher/releases/tag/2021-06-26_02

**Comment by Achime11** [comment]
I just did the update directly from the application (everything seems to have updated the application properly). 
I tested again with the same 3 accounts. From my tests, I realized that I just have to re-add the accounts in the application because you changed the saved stuff.
Now everything is working properly, well done. :)))
