### ISSUE TITLE
Account Names with < and > characters are parsed as HTML

### ISSUE THREAD

**Issue by lnx00** [TcNobo/TcNo-Acc-Switcher#42]
I've found out that Account Names containing < and > will be parsed as HTML.
This causes the account name to be invisible as you can see here:
![Screenshot](https://i.imgur.com/GFDJ9Ce.png)

In this example i've tried the name < LNX > and now it's invisible.

**Comment by TcNobo** [comment]
Thanks for letting me know, I hadn't thought of this.
I will get to patching this with the next update.

At least it's not an immediate security vulnerability as:
-The account switcher's browser isn't something you actively use, so there's no personal data/details saved & accessible.
-Browsers are limited with how much data they can access off the bat.
-And most importantly it reads local files meaning a bad actor would need access to your local files... meaning a device is already more than compromised.

**Comment by TcNobo** [comment]
Fixed in the latest commit https://github.com/TcNobo/TcNo-Acc-Switcher/commit/cfa621e40c70523bd10e46969e51a1380d67bff4
Will be pushed with the next update soon.

**Comment by TcNobo** [comment]
Update released. Do let me know if you have any other issues, and if this issue still persists.
Thanks for your help improving the program.
https://github.com/TcNobo/TcNo-Acc-Switcher/releases/tag/2021-06-26_02

**Comment by lnx00** [comment]
It's working fine now. Thank you very much for all the work you have done with the Account Switcher!
