### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by Vic2077** [TcNobo/TcNo-Acc-Switcher#45]
When it comes to installing WebView2 it says that "Installator's archive is damaged or invalid. Download Microsoft Edge once again.", or something like that, then downloads the new one and says the same. I can't proceed past this step. =(

**Comment by Vic2077** [comment]
![QIP Shot - Screen 00011991 05 07 21 05-47-34](https://user-images.githubusercontent.com/22431284/124411479-47b5fd80-dd55-11eb-9e22-14e0462b34dc.png)

**Comment by TcNobo** [comment]
I've never seen this before... 
You can find WebView 2 downloads on Microsoft from here: https://developer.microsoft.com/en-us/microsoft-edge/webview2/

The version the program links to is the "Evergreen Bootstrapper", the option to the far left. It's a small file that downloads the rest of the files.
Try downloading the "Evergreen Standalone Installer", x64. The link right next to it.
Else, try the latest "Fixed Version". At the time of writing is 91.0.864.64 .

Let me know if that fixes your issue.

**Comment by Vic2077** [comment]
"Evergreen Standalone Installer", x64 also gives an error message: "The Installer was unable to unpack the archive. Download Microsoft Edge once again."
![QIP Shot - Screen 00012008 06 07 21 08-42-34](https://user-images.githubusercontent.com/22431284/124548435-63dd9b80-de36-11eb-801b-4ca11794c9c2.png)

**Comment by Vic2077** [comment]
The "Fixed Version" 91.0.864.64 is some sort of .cab file. Where do I put or how do I open that?

**Comment by Vic2077** [comment]
By the way, the original MicrosoftEdgeWebview2Setup.exe is working differently today: the window does some operations for some time,  and then automatically disappears without any error or successful completion messages.
But the program itself is still just a black rectangle with nothing on it (although, the mouse cursorchanges to a "hand" when I hover it over certain areas of that rectangle, indicating that there should probably be some active elements of the program in those areas, which are not being drawn properly.

Is this app even supposed to work on Windows 7 x64?

**Comment by TcNobo** [comment]
According to Microsoft's [Supported Platforms list](https://docs.microsoft.com/en-us/microsoft-edge/webview2/#supported-platforms), Windows 7 support is listed, or at least for "the same support cycle as Microsoft Edge... Which says they will support Edge on Windows 7 until January 15, 2021. [Info here](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-supported-operating-systems).

So yes, it should be supported.

Unfortunately, this software isn't made or maintained by me, it's Microsoft doing that... The most active 'bug report' page I can find is this [WebView2 Feedback](https://github.com/MicrosoftEdge/WebView2Feedback) page. Searching for Windows 7 shows [some results](https://github.com/MicrosoftEdge/WebView2Feedback/issues?page=2&q=is%3Aissue+is%3Aopen). [one looking promising](https://github.com/MicrosoftEdge/WebView2Feedback/issues/1329), but seems unrelated.


I installed Windows 7 x64 onto a virtual machine, and it installed just fine. Everything installed as it does on Windows 10... However, when it runs, it opens the same blank window as you see. The WebView2 is only partially working. You can right-click and interact with the page, but it's completely blank. Why? I have no idea... This program does only officially support Windows 10+, but I'd like to get it working with 7 as well, as some people still use it.

From what I've found, to install .CAB files:
1. Open Command Prompt as Administrator
2. Enter: `dism /online /add-package /packagepath:"<PUT-CAB-FILE-PATH-HERE>" `, substituting that last bit for the .cab's path. For example: `dism /online /add-package /packagepath:"C:\Users\TCNO\Downloads\Edge.cab".

Let me know if installing from the 'fixed version's CAB file works properly, or if you make other progress.

**Comment by Vic2077** [comment]
Okay, I've tried to install the "fixed version" .cab. It has also failed to install.
[dism.log](https://github.com/TcNobo/TcNo-Acc-Switcher/files/6794165/dism.log)

**Comment by TcNobo** [comment]
You can use the [CLI](https://github.com/TcNobo/TcNo-Acc-Switcher/wiki/CLI-&-Protocol) to change accounts through the command line... But I have no idea if it'll work without launching the actual program.

That update I mentioned should be out now, so just download the latest version from GitHub and install it.
You can then run `TcNo-Acc-Switcher-Server.exe`  and use the program through the URL listed in that window, usually something along the lines of `localhost:5000`. I'm not sure how much of the program will work through a browser. Changing icons through the Right-Click menu shouldn't work, and small things like that.

Unfortunately with not being able to install WebView2... It's a Microsoft product and I'm not able to help...
[This (https://github.com/MicrosoftEdge/WebView2Feedback/issues)](https://github.com/MicrosoftEdge/WebView2Feedback/issues) seems to be Microsoft's official support hub for everything WebView2, so you'd likely find an answer here posting as much info as possible. Just failing to install WebView2. Most of everything seems to get an answer after a few days.

**Comment by Vic2077** [comment]
Thanks. Well, I'll try that, but if it won't work, I guess I'll just give up on this program and search for alternatives that will work, or just resort back to using ASF, diffrent Chrome profiles for each of my Steam accounts and manual relogging in the Steam Client (if needed), until I'll get a new SSD and nstall a fresh copy of Win10 on it.
My OS is very old and a lot of things is already broken it it (especially Microsoft-related stuff) so it needs a re-installation for a long time already, anyway...
And, well, I guess this program is just one of the things that don't work properly in it...

**Comment by Vic2077** [comment]
Where that localhost address should be shown?
TcNo-Acc-Switcher-Server.exe closes right after startup with no warnings or anything. (cmd window pops up for a split second, then disappears, and nothing else hapens, after I doubleclick the .exe)

**Comment by TcNobo** [comment]
Then it's still broken. Make sure you've downloaded a fresh copy of the program from this GitHub.
It should look like this 
![image](https://user-images.githubusercontent.com/10319195/125157645-87715080-e16c-11eb-979e-04432397901d.png)

Try typing CMD into the folder path, and hit Enter 
![image](https://user-images.githubusercontent.com/10319195/125157660-9b1cb700-e16c-11eb-9a2a-d817257e33ae.png)

Type `TcNo-Acc-Switcher-Server.exe`, the same as the program and hit Enter to make sure it doesn't disappear immediately.
![image](https://user-images.githubusercontent.com/10319195/125157676-b1c30e00-e16c-11eb-980f-7f277056705e.png)

You should then either see it work or hopefully an error message you can copy/paste into this thread.

**Comment by Vic2077** [comment]
Nothing happens:
D:\!Downloads\Pics\QIP Shot\QIP Shot - Screen 00012103 14.07.21 12-54-16.png

**Comment by TcNobo** [comment]
:/ alright...
It seems like this program only really works on Windows 10 for now. I'll try and improve Windows 7 compatibility.
If anyone has anything to add, I'm all ears.

**Comment by TcNobo** [comment]
Got a response on the aforementioned thread I posted with Microsoft... More info is needed.

Hit `Start+R`, type `dxdiag` and hit enter. This brings up some system info (after some time). Screenshot the `System` tab, as well as `Display 1`, and send them here.
If any of the other Display tabs show a different graphics card, screenshot those too

**Comment by Vic2077** [comment]
![QIP Shot - Screen 00012468 21 07 21 20-11-14](https://user-images.githubusercontent.com/22431284/126530798-6e40c5a8-1152-406e-b797-b8eca9ed8621.png)
![QIP Shot - Screen 00012469 21 07 21 20-11-23](https://user-images.githubusercontent.com/22431284/126530803-5d974754-59ea-4b5c-a069-1e39d1d72893.png)
![QIP Shot - Screen 00012470 21 07 21 20-11-31](https://user-images.githubusercontent.com/22431284/126530808-f86cd2ac-302b-48c7-b04e-e19c88954794.png)

**Comment by TcNobo** [comment]
@Vic2077 
I have almost finished the CEF alternative browser for the account switcher - fixing the "empty screen issue". Do download the test version from here: https://tcno.co/Projects/AccSwitcher/CEFTemp/TcNo-Acc-Switcher-CEFBeta.7z

**Short version:** Please run it 3 times, on the third error it downloads some missing files, and should launch again with a different 'browser', and should work properly. Let me know if you have any luck with this.

**Long version:**
Extract and run it from any folder, and let me know if it works any better. It should be fine.
The screen will be blank on the first launch, and an error should show saying "download WebView"  - Click cancel.
It creates a file called `WebViewNotInstalled` in the install directory. The second launch shows the error again, allowing users who missed the original WebView download to use it normally now. If WebView doesn't work - which it doesn't for you: Click Cancel and launch again.
This time the updater should start after clicking OK (a different error will show saying it will now download CEF). The updater should start and download, then extract a file.

This file is downloaded: https://tcno.co/Projects/AccSwitcher/updates/CEF.7z, then extracted into `TcNo-Acc-Switcher\runtimes\win-x64\native`. AND `%AppDaata%\TcNo Account Switcher\WindowSettings.json` is edited to include the line: `"ActiveBrowser": "CEF"`, instead of `"ActiveBrowser": "WebView"` (also newly added with this new update).

**Comment by Vic2077** [comment]
Hi. How do I run it? Double clicking TcNo-Acc-Switcher.exe does nothing (I
even don't see any related activity in the Task Manager).

сб, 6 нояб. 2021 г. в 18:16, Wesley Pyburn (TechNobo) <
***@***.***>:

**Comment by TcNobo** [comment]
Alright. Quick workaround. Open the Updater folder, wherever you extracted it to.
1. Click at the top (here): ![image](https://user-images.githubusercontent.com/10319195/140617278-59a3a278-cd15-497d-ad2a-6c79dd083a96.png)
2. type `TcNo-Acc-Switcher-Updater.exe downloadCEF`, and hit enter.
3. Start+R and type `%AppData%\TcNo Account Switcher`, then hit Enter.
4. Create a new file called `WindowSettings.json`, open it with Notepad, then enter: `{"ActiveBrowser": "CEF"}` and save it.
5. Run `TcNo-Acc-Switcher.exe`

Let me know if things work.

**Comment by Vic2077** [comment]
#2 and #5 gave me this:
[image: QIP Shot - Screen 00014079 06.11.21 20-16-03.png]
%AppData%\TcNo Account already had  WindowSettings.json in it

{
  "WindowsAccent": false,
  "StreamerModeEnabled": true,
  "ServerPort": 38604,
  "WindowSize": "800, 450",
  "Version": "2021-07-01_00",
  "DisabledPlatforms": [],
  "TrayMinimizeNotExit": false,
  "ActiveTheme": "Dracula_Cyan",
  "ActiveBrowser": "WebView",
  "Language": "",
  "ShownMinimizedNotification": false,
  "StartCentered": false
}

I've renamed it before doing #4

сб, 6 нояб. 2021 г. в 19:49, Wesley Pyburn (TechNobo) <
***@***.***>:

**Comment by TcNobo** [comment]
The screenshot didn't upload properly :/
However you can just edit the line `"ActiveBrowser": "WebView"` to be `"ActiveBrowser": "CEF"`

**Comment by TcNobo** [comment]
Ah yes, sorry. it's not working because it's missing new theme files -- Working on an update for that too.
Download and extract this .7z into `%AppData%\TcNo Account Switcher\WindowSettings.json`. It has a `themes` folder in it, with the missing files in it.
https://tcno.co/Projects/AccSwitcher/CEFTemp/AppData.7z

It also has the `WindowSettings.json` file in it.

**Comment by Vic2077** [comment]
Okay, I guess it worked. The app started and detected my main Steam account
that I was logged in with at the moment, but when I'm trying to add more
accounts to the app or to log in to Steam with my main account that is
already in the app using the app, my Steam client seems to get some kind of
problem connecting to the servers or something, because it can't open my
Profile or Librabry.
[image: QIP Shot - Screen 00014084 06.11.21 21-12-38.png]

сб, 6 нояб. 2021 г. в 20:36, Wesley Pyburn (TechNobo) <
***@***.***>:

**Comment by TcNobo** [comment]
Alright, this is now fully released with update 2021-11-20_00. Download here: https://github.com/TcNobo/TcNo-Acc-Switcher/releases/tag/2021-11-20_00

I'm closing this issue as if you're getting a blue screen on launch, simply click Yes when prompted if you want to use CEF ~ Or, if you're not prompted:
- Go to `%AppData%\TcNo Account Switcher`, open `WindowSettings.json`.
- Make sure it includes the line `"ActiveBrowser": "CEF",`.
If you don't know how to include that line, you can replace the entire file with this text:
`{"ActiveBrowser": "CEF"}`
