### ISSUE TITLE
Can I add support for Chinese?

### ISSUE THREAD

**Issue by KKingwang** [TcNobo/TcNo-Acc-Switcher#46]
Software is very easy to use, but because English is not very good, so can you add support for Chinese? Thank you!)

**Comment by TcNobo** [comment]
Support for other languages is planned. I don't speak them so I need help from the community. I do need to finish adding all of the text here: https://crowdin.com/project/tcno-account-switcher so it can be translated.

I can translate with Google Translate just to start, and the community can correct OR I can wait for the community to fill in translations on the site above.

**Comment by TcNobo** [comment]
Please see the project on [Crowdin ](https://crowdin.com/translate/tcno-account-switcher/)(crowd-sourced translation).

I've used their auto translator to translate as a start, and need someone who speaks each language to verify it's correct. After making an account you can correct items that don't look right.

Find the Chinese Simplified translations, here: https://crowdin.com/project/tcno-account-switcher/zh-CN

Do let me know if it's ~good enough~.

**Comment by deluxghost** [comment]
I updated and verified all the Chinese translations. You can set me as a proofreader if you need one

**Comment by TcNobo** [comment]
Awesome, thanks for your contributions @deluxghost. I've added you and the few others who've helped out to Proofreaders.

**Comment by deluxghost** [comment]
FYI I cannot really help with Traditional Chinese, it's slightly different from Simplified Chinese.
