### ISSUE TITLE
Silent launch option?

### ISSUE THREAD

**Issue by Rozrty** [TcNobo/TcNo-Acc-Switcher#48]
Steam program lets you have steam be minimized to tray upon start up. Could that option be added to this account switcher too?

https://support.steampowered.com/kb_article.php?ref=5623-QOSV-5250

"-silent - Launches Steam to the system tray only. Normal Steam windows will only appear after clicking the system tray icon. If a password is not stored, the normal login window will still be displayed."

**Comment by TcNobo** [comment]
This could be added with the right-click menu, and as a "default" for switching accounts, as well as through the command line/protocol - for account shortcuts.

How would you use this feature? Just right-clicking and switching accounts? or more through shortcuts or other programs?

**Comment by Rozrty** [comment]
Thanks for the reply, I love your work.

Honestly, I use desktop shortcuts to switch accounts. I'm not sure what other users would prefer but having it as an option for shortcuts would be nice.

**Comment by TcNobo** [comment]
You should now be able to add a space, followed by `-silent` and other commands for Steam, and other platforms.
Download the latest release via the update banner in the app, or from here: https://github.com/TcNobo/TcNo-Acc-Switcher/releases/tag/2021-07-23_00

**Comment by Rozrty** [comment]
Works on my end, thank you very much for the new update.
