### ISSUE TITLE
Tray Application Not Working

### ISSUE THREAD

**Issue by thomas-williams** [TcNobo/TcNo-Acc-Switcher#5]
I had everything working just last week, but when I got back to my PC today and booted things back up the tray icon application started throwing an error about missing the required .NET framework. I have made sure the specified version is installed multiple times, including the alternate version mentioned in the Requirements.txt file. I have also reinstalled the whole application multiple times, and it still does not work. I have done my best to check that I have 3.1.1 installed, but I only have items in my registry for 3.0 and 3.5. I'm not sure if 3.1.1 would be grouped into 3.0, but if there is a way to check that would be great.

**Comment by igoRoots** [comment]
The same for me :/   It's not working anymore.

**Comment by TcNobo** [comment]
No idea what could be causing this other than something in the `%temp%` folder.
I've given up with .NET Core, and I'm moving it to .NET Framework 4.8. The transition has been good, so far. I'm working on adding features and improving error-prone functions as well.

This should solve issues that come with files in`%temp%` being cleared by other programs, as it will be installed in its own directory. You'll probably extract it to a folder in your desktop for example.

I originally switched to .NET Core with hopes of it working well on other platforms but never got around to adding functionality as I don't use those platforms. It seems Microsoft is also moving away from .NET Core, and others with the upcoming .NET 5.

I haven't had much time to work on the project, but good progress is being made. A working version should be available within the next few days :)
Some things still need to be added to the tray icon and built to work with the Steam account switcher.

Current changes can be seen on the [Origin-test branch](https://github.com/TcNobo/TcNo-Acc-Switcher/tree/Origin-test) -- Yes, other platforms to come soon :)

**Comment by igoRoots** [comment]
To be honest, I don't know what's .NET, hahaha, but I think it's a programming language.. ^^
Anyway, thanks for the answer, you're doing a great job!
I'm looking forward for new version  :)

**Comment by TcNobo** [comment]
New Beta release is out. Should fix a lot of issues, including the ones above :)
Download a .zip, extract the folder, open the folder and then `TcNo Account Switcher.exe`
https://github.com/TcNobo/TcNo-Acc-Switcher/releases/tag/3.0.0a

**Comment by thomas-williams** [comment]
The new app works great and install was easy. Great work! However I'm not seeing the minimize to tray option, or the standalone tray app version. Am I missing something?

**Comment by TcNobo** [comment]
There isn't a minimize to tray option just yet, though it's a good suggestion I shall add in the future.
To use the program from the tray, make sure "Start with Windows" is checked, and the tray icon will appear on the next login.
![image](https://user-images.githubusercontent.com/10319195/85414567-8d4dc100-b56c-11ea-9dae-d241f851e955.png)

For now, you can start it manually from the Start Menu by clicking "TcNo Account Switcher - Steam tray" (Assuming you have "Start menu shortcut" checked)
Start menu shortcut: 
![image](https://user-images.githubusercontent.com/10319195/85414722-c0905000-b56c-11ea-8de2-0d0830c057bf.png)
Create Start Menu shortcuts: 
![image](https://user-images.githubusercontent.com/10319195/85414782-d6057a00-b56c-11ea-80e2-ce0df06ea596.png)

**Comment by TcNobo** [comment]
No response in a month. Considered solved :)
