### ISSUE TITLE
Can't use the Discord account switcher with Discord Canary

### ISSUE THREAD

**Issue by RealRedcodi** [TcNobo/TcNo-Acc-Switcher#54]
It cannot locate, or let you select the Discord Canary executable. 
![image](https://user-images.githubusercontent.com/21988518/127369618-3b73c142-bf91-4560-a0ee-9b760ae7b26a.png)
![image](https://user-images.githubusercontent.com/21988518/127369677-638dc369-97e5-4772-9776-5191103f1f2a.png)

Edit: It also has like a 50% chance of crashing when you click the Discord button 
![image](https://user-images.githubusercontent.com/21988518/127370033-d63c8383-2e47-4039-a8a6-cc9140066b2f.png)

**Comment by RealRedcodi** [comment]
Also, the executable's name is `discordcanary.exe`

**Comment by TcNobo** [comment]
Yes, this currently only works with the 'normal' Discord.
I need to figure out how, and if I'll include support for other Discord types. (PTB and Canary).

When I find time, it would probably be possible to Right-Click the Discord icon in the main menu and select Discord, Discord PTB and Discord Canary...

**Comment by RealRedcodi** [comment]
> Yes, this currently only works with the 'normal' Discord.
> I need to figure out how, and if I'll include support for other Discord types. (PTB and Canary).
> 
> When I find time, it would probably be possible to Right-Click the Discord icon in the main menu and select Discord, Discord PTB and Discord Canary...

Got it, thanks!

**Comment by TcNobo** [comment]
A similar feature is coming soon in the next major update. I'm closing this, for now, to clean up issues.
See the above link.
