### ISSUE TITLE
3 "accounts" i didnt mean to add cannot be removed

### ISSUE THREAD

**Issue by burner2121** [TcNobo/TcNo-Acc-Switcher#59]
When adding an account, I accidentally copied the code needed to paste into discord and pasted it into the "enter name of the account" bar instead of the code needed to add the account properly. Now I have 4 accounts I cant delete for some reason. 

![image](https://user-images.githubusercontent.com/88690000/128783040-7374b37d-29e9-412b-9300-5305d92da966.png)

**Comment by TcNobo** [comment]
That's odd, will look into patching this.
To solve the issue now:
1. Head to `%AppData%\TcNo Account Switcher\LoginCache\Discord\`
2. Delete the folders of these broken accounts
3. (if you have no other accounts) delete `ids.json`

OR 3. (if you have other accounts) Each account has an ID and a username, separated by a colon, both surrounded by quotation marks. You need to remove the ID and username of each account with the quotes, and the comma at the end between accounts (if no account follows it). Keep the format: `{"ABC":"User:123", "BCD":"User2:234"}`

**Comment by TcNobo** [comment]
This is fixed in the latest release. Closing this thread.
If you encounter any issues, respond here to reopen this thread.
https://github.com/TcNobo/TcNo-Acc-Switcher/releases/tag/2021-11-21_00
