### ISSUE TITLE
Riot Games Switcher doesn't work at all

### ISSUE THREAD

**Issue by Gorgrak** [TcNobo/TcNo-Acc-Switcher#60]
i try to use the desktop shortcuts to switch between accounts for league of legends. EVERY TIME i have to completely re-enter my username and password and click "stay signed in". 0% working. how to fix?

**Comment by TcNobo** [comment]
Unfortunately, Ubisoft and Riot are the 2 least-stable switchers in this program. It is something I want to work on improving, but it's very difficult when they work almost flawlessly for me currently.

I've just tested the Riot account switcher on 2 devices, and both worked fine... What system are you running? Press `Start+R` and enter "dxdiag", then click OK. Screenshot the `System` tab and send it here so I can get a good idea of the computer you're running. If I spin up a virtual machine in your OS version I may be able to solve the issue, if it breaks for me as well - hopefully.

**Comment by Gorgrak** [comment]
Thanks for the reply! Sorry for not replying until now. Here's my system. Does it matter that I don't have your tool running but merely run directly from the shortcuts I've made?

![08_12_21 @11_06_16](https://user-images.githubusercontent.com/17152698/129303487-9d5007bd-43fe-4883-b619-822425fbb4eb.PNG)

**Comment by TcNobo** [comment]
I assume shortcuts to switch accounts? If so, it starts the program to swap.
If you're talking about say the Valorant shortcut, then it's the same as launching it from the switcher.

**Comment by Gorgrak** [comment]
Yessir; I'm only using League of Legends atm. I've got 2 different accounts I play with and have made 2 desktop shortcuts to use. Activating either shortcut doesn't populate the username or password fields with any information or check the "stay signed in" box when the login page/screen loads.

Additional information: Windows is installed on my C drive but all my media (music, movies, video games) are installed on my E drive. Could this be the culprit?

**Comment by TcNobo** [comment]
Yes, this program does none of that, by design. It skips login completely.

You sign in once, with "Stay signed in" checked, and NEVER click logout in any Riot apps.
Use the TcNo Account Switcher's "Add New" button to log in to another account, assuming you saved any new accounts you logged into.

**Comment by Gorgrak** [comment]
Okay I did some more testing. I removed my accounts and re-added them. It's now working perfectly (both from your program's account switcher screen as well as when the account switcher is closed and only using the desktop shortcuts)! Not sure what the problem was?

**Comment by TcNobo** [comment]
No idea, glad you got it working again.
The only thing I've heard is with >5 accounts some odd issues happen, where all 'forget password' though I'm sure it's a Riot-side limitation if anything.
