### ISSUE TITLE
GUI not centered

### ISSUE THREAD

**Issue by dlartigu** [TcNobo/TcNo-Acc-Switcher#61]
Hello and thanks for your work.
The main GUI isn't centered, even after centering and then closing, still it's kind of random position top left.
I've used WindowManager to create a rule to get it centered but even with that, it's still not working.

BTW, do you plan to add Valorant ? Caus' it doesn't work as a riot account for me.

Thanks

**Comment by TcNobo** [comment]
The GUI opens randomly on your screen when you open the program? I haven't set it to centre or anything, it opens like any other window at the moment.

Valorant and all other Riot games are supported but do see this for more info: https://github.com/TcNobo/TcNo-Acc-Switcher/issues/60. You can post a screenshot there too to let me know more info :)

**Comment by dlartigu** [comment]
Yup it's randomly or kinda all the time like the screenshot below.
https://ibb.co/K6vtdYG

Okay I'm gonna take a look for Valorant too :)

**Comment by dlartigu** [comment]
Yes I know that cascade effect lol :)
It'll be great for people like me who like things to be centered hahah
Again, thanks a lot for your work

**Comment by TcNobo** [comment]
Implemented. https://github.com/TcNobo/TcNo-Acc-Switcher/releases/tag/2021-09-28_00
