### ISSUE TITLE
Error "could not load Steam/config/loginusers.vdf" everytime when opening through steam link

### ISSUE THREAD

**Issue by marcinkolos** [TcNobo/TcNo-Acc-Switcher#62]
Error "could not load Steam/config/loginusers.vdf" everytime when opening through steam link. It seems like it forgets settings like steam location.
![obraz](https://user-images.githubusercontent.com/56196429/129100810-9f4b2823-1be4-43aa-9f9e-48f3c0b65226.png)

**Comment by TcNobo** [comment]
After you manually set Steam's location in the options screen, does it start working again? Maybe after a restart?

**Comment by marcinkolos** [comment]
It works till I restart. After relaunch I have to set steam location manually again.

**Comment by TcNobo** [comment]
Are you still having this issue currently, with the latest update? What do you mean by opening through Steam Link... Like this [Steam Link (store.steampowered.com)](https://store.steampowered.com/app/353380/Steam_Link/)?

**Comment by marcinkolos** [comment]
[https://www.youtube.com/watch?v=X7RbI24E5u4](https://www.youtube.com/watch?v=X7RbI24E5u4)

**Comment by TcNobo** [comment]
Finally got around to fixing this. It should be patched in the next update.
