### ISSUE TITLE
Why does discord switcher require password?

### ISSUE THREAD

**Issue by Rozrty** [TcNobo/TcNo-Acc-Switcher#65]
Is there a chance this could be made optional?  Just curious because security isn't something I need. It's okay if you don't want to change how it works though.

**Comment by TcNobo** [comment]
I'll paraphrase here.
Discord 'account stealers' and malware alike browse to where your Discord token/cookies are, and send them to an attacker, stealing your account.
This program collects those files that give you access to your account, allowing you to switch accounts. It simply moves in files from another account, and stores file from others in a folder.

Unlike programs that save access to your account unprotected, I would at least like to make it much more difficult for an attacker to steal accounts collected by this program. Hence, the password. The files are useless without the correct password, keeping multiple accounts safe, while only 1 account is "unsafe" at a time -- The one logged in on a Discord client, where it is usually vulnerable.

The password can be as simple as one character. Files encrypted by a 1-letter password and a 60-letter password appear similar. The possibility that someone would need to brute force possibly thousands or millions of passwords is a good deterrent in my opinion.

**Comment by Rozrty** [comment]
Ok, that makes perfect sense. You can close the issue. Sorry for the stupid question.

**Comment by TcNobo** [comment]
No questions are stupid. Stay curious.
