### ISSUE TITLE
TcNo-Acc-Switcher.exe

### ISSUE THREAD

**Issue by axelnieves2012** [TcNobo/TcNo-Acc-Switcher#67]
To run this application, you must install .NET.
The framework -Microsoft.WindowsDesktop.App' version '5.0.0' was not found.
Would you like to download it?

I think this is due your program checks for version 5.0.0
BUT current .NET version is 5.0.9 (EEEEEEEEEEEEEEPIC FAIL!!!).

![image](https://user-images.githubusercontent.com/35415189/130542555-bb5fd0de-b54c-48c9-90c9-f12afc3275a8.png)

**Comment by TcNobo** [comment]
I must have missed the Comment button when I responded a few days ago, sorry.

You are missing 1 or more of the 3 (three) requirements. Make sure you have everything downloaded:
https://github.com/TcNobo/TcNo-Acc-Switcher/wiki#1-installing-required-runtimes

### 1. Installing required runtimes:
**If you use the installer:** The required runtimes will automatically be downloaded and installed.
**If you are NOT using the installer:** Run `_FIRST_RUN.exe` on a computer to bring up the same window as in the installer, where runtimes are downloaded and installed.
**Manual runtime install:**
-   **WebView2 Runtime**:  Click [HERE](https://go.microsoft.com/fwlink/p/?LinkId=2124703) and install.
-   **Microsoft .NET 5 Desktop Runtime AND: ASP.NET Core 5.0 Runtime:** Click [HERE](https://dotnet.microsoft.com/download/dotnet/5.0/runtime) and click `x64`, as well as `Download Hosting Bundle`. **See below:**
    ![Buttons to click for .NET Desktop & ASP.NET runtime](https://i.imgur.com/f4e14Mr.png)

**Comment by axelnieves2012** [comment]
thanks. You were right. Some of these programs were not installed. It's not really clear on description what exactly we have to download/install.
It is working now. My bad.
