### ISSUE TITLE
Got Error when open TCNo Switcher

### ISSUE THREAD

**Issue by thienha1** [TcNobo/TcNo-Acc-Switcher#68]
Yesterday i opened this normal, today i dunno why it occured error like this:
![Untitled](https://user-images.githubusercontent.com/18132856/130902571-7fdc6eba-5a0d-44e9-b940-e5a74fe0ef01.png)
I wonder if you find out what occured error and i should be say 'Thanks'.

**Comment by thienha1** [comment]
I just reinstall windows and it works

**Comment by TcNobo** [comment]
Awesome. Good to know.
