### ISSUE TITLE
Toggle off "TcNo Account Switcher Notice"

### ISSUE THREAD

**Issue by TVKEN** [TcNobo/TcNo-Acc-Switcher#69]
Add the option to toggle off the TcNo Account Switcher Notice that pops up when the app is already running and double-clicking the Desktop shortcut to bring up the app. The feature is kinda annoying to be honest. 
![Untitled](https://user-images.githubusercontent.com/89789581/131352747-a68141c6-36d5-4499-92ee-99c022d902e7.png)

**Comment by TcNobo** [comment]
Noted :) 
Will add this to the todo list

**Comment by TcNobo** [comment]
Implemented. https://github.com/TcNobo/TcNo-Acc-Switcher/releases/tag/2021-09-28_00
