### ISSUE TITLE
Error when opening discord account switcher

### ISSUE THREAD

**Issue by lakeuwu** [TcNobo/TcNo-Acc-Switcher#70]
I went to click the discord button and it didnt work so i opened the console and saw this

![image](https://user-images.githubusercontent.com/73145172/132113739-e5342e70-2b10-494d-9383-8a5e00094160.png)

any ideas how to fix this?

**Comment by TcNobo** [comment]
I haven't seen this before.
Check `%LocalAppData%\Discord` and see the folders named `app-1.0.0000` for example. The program looks for the 'latest' version of Discord to use that .exe. Something is going wrong here.

Would you mind uploading a screenshot of that folder? Discord may be installed in another location as well, and partially left behind? Not too sure what could be going on here.

Seems to be breaking in the logic just after it removes "app-" from the text, and then splits each number based on where the `.` is. While trying to convert each part separated by a `.` into a number, something isn't a number for some reason or something like that.

**Comment by lakeuwu** [comment]
Nevermind I fixed it by reinstalling discord sorry for the late response!
