### ISSUE TITLE
[Suggestion] EA App addition

### ISSUE THREAD

**Issue by Carbonixx** [TcNobo/TcNo-Acc-Switcher#71]
The new EA App is in beta to replace the origin app and runs pretty smoothly, would it be possible to add it?

**Comment by TcNobo** [comment]
Yes, this is planned.
Unfortunately, I've been very busy and distracted from this, so I haven't had time to add it.

**Comment by TcNobo** [comment]
This platform was added with version 5.0 (Jan 2022). Please download and check if it works.
Re-open this issue if you have further comment :)
