### ISSUE TITLE
Stopped working today

### ISSUE THREAD

**Issue by RyujinFox** [TcNobo/TcNo-Acc-Switcher#75]
I've been using this program for all available platforms (except riot games, since i didn't feel like going out of my way to add it yet).
And it has worked wonderfully for 2 weeks, but lately it'd been saying that there was already an instance of the client open whenever i would run it, and show me various error messages, i would not think too much of them since the client would work just fine afterwards anyways, but today i haven't been able to open the software at all. I've tried starting the software with administrator privileges, but no difference, my mouse would show the loading symbol, and my pc would feel slow, meaning that the cpu was in some sort of process, but the program would not open. After waiting 5 minutes or so, windows dialog would ask me if the program ran as expected. This is sadly all the info i can give. I've restarted my pc several times, and also tried reinstalling to no avail.

**Comment by TcNobo** [comment]
Odd...
1. If you check Task Manager, do you see any other `TcNo...` tasks running?
2. You can try renaming the `%AppData%\TcNo Account Switcher` folder, "resetting" all the program's settings. If it starts working, then the issue is in there, and going through each settings file to get back would be the easiest - Otherwise, I'm not too sure...

Do try these above and let me know if it doesn't start working.

**Comment by RyujinFox** [comment]
I have not been able to find anything in task manager, and haven't gotten around to trying the appdata thing you mentioned above (i will do so right now), didn't see your response.

I tried launching the TcNo-Acc-Switcher-Tray.exe, which actually launched and would display my profiles in each section.
I tried using it to switch my discord account. The process started, it asked for my discord switcher password in cmd, then proceeded to close discord, but never got any further.

I'll get back to you with my findings.

**Comment by RyujinFox** [comment]
Welp.. It seems that the issue was solved with renaming the appdata folder, 
no idea why yet.. but at least i can use the software while i figure that out.

Cheers!

**Comment by TcNobo** [comment]
Good to hear.
Sometimes the program seems to just empty out those `.json` files that hold all the settings... They're simple text files.
If you'd like you can `.zip` all the files in the broken folder, and send them to me either through Discord TechNobo#1337 or by emailing me technobo@tcno.co - other than the `EBWebView` and `LoginCache` folder, so I can look through them for anything odd.
