### ISSUE TITLE
launch options 

### ISSUE THREAD

**Issue by BeigeAnimal** [TcNobo/TcNo-Acc-Switcher#76]
I know there is like only 4 launch options for Steam [at least shown here](https://help.steampowered.com/en/faqs/view/0188-6BB7-D467-08E1)
The main one I'm concerned for is ``-tcp`` 
Would you be willing to add to either add custom launch options or at least tcp for shortcuts, some people may have a problem with udp.
For me it causes it to take a really long time to sign in and it constantly disconnects me from steam chat randomly.

**Comment by TcNobo** [comment]
This is already a feature for shortcuts: https://github.com/TcNobo/TcNo-Acc-Switcher/wiki/CLI-&-Protocol#optional-arguments
Just add `-tcp` to the end of the account switcher's shortcuts.

![image](https://user-images.githubusercontent.com/10319195/133921347-c445cf27-6a60-4d59-a965-3969937dadeb.png)

![image](https://user-images.githubusercontent.com/10319195/133921337-211a7e42-46ec-4851-b5b2-db4293be0866.png)

I do want to add a 'Global arguments' or something similar section to add arguments to every account on a platform. I will remember this.

**Comment by BeigeAnimal** [comment]
Oh ty, sorry for being blind.

**Comment by TcNobo** [comment]
No problem :)
No question is stupid. Glad you got it working
