### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Xxforlife** [TcNobo/TcNo-Acc-Switcher#78]
I just recently installed it and I got no errors when installing and it works perfectly fine with discord but when trying it with steam, steam gives the error, couldn't find steamui.dll. Some extra info if needed, I have steam on a portable hard drive, I can confirm that I chose my directory correctly because when I hit the open steam folder button in settings it opens it to the steam folder. steam works perfectly fine without the switcher so I'm guessing there is something im missing or it might just be an error. I would also like to note that I used the quick installer and not the zip. I hope this is enough info to get this fixed if it is an error or the get help if its just me not realized a really simple mistake that I might've made.

**Comment by Xxforlife** [comment]
I noticed someone had the same error a few days ago and was also using a secondary hard drive though i tried their fix and it didn't seem to work.

**Comment by TcNobo** [comment]
Issue #58. Thanks for more info :) Will continue with that issue if more is needed.
