### ISSUE TITLE
New issue

### ISSUE THREAD

**Issue by vaggosbest** [TcNobo/TcNo-Acc-Switcher#79]
The app opens normally but when i choose the steam option there is a message popping at the bottom of the app saying "An error has occurred. This application may no longer respond until reloaded. Reload" I press reload but nothing happens. I don't use the other features besides the steam option and the app has been working fine all summer.

**Comment by TcNobo** [comment]
Hit `Ctrl+Shift+I` and go to the `Console` tab after getting that message.
Send a screenshot of the error message showing in the `Console` tab here :)

**Comment by vaggosbest** [comment]
![Screenshot 2021-09-26 184137](https://user-images.githubusercontent.com/73291764/134814673-0c96c764-02dd-4c47-81d5-a9c60ab0d5ca.png)

**Comment by TcNobo** [comment]
Thanks for the report, working on a fix for this.
Temporary fix: Go to `%AppData%\TcNo Account Switcher` and delete `SteamSettings.json`

**Comment by vaggosbest** [comment]
Thank you, it works for now!
