### ISSUE TITLE
2FA (Mobile Authenticator) compatibility

### ISSUE THREAD

**Issue by sayonaraLulw** [TcNobo/TcNo-Acc-Switcher#80]
I'm not sure about that but I think it won't autologin if I'm using the mobile authenticator on Steam..

**Comment by suhasholla** [comment]
works for me, added multiple accounts which has 2FA mobile authenticator enabled, but use Steam Desktop Authenticator

**Comment by TcNobo** [comment]
As long as you have Remember Password checked, it should work whether Steam Authenticator, Steam Guard and other things are enabled.
If you're able to restart your computer after logging in and still be logged in: The account switcher should work for you.

I would usually close these but I'll leave it open for a while :)

**Comment by sayonaraLulw** [comment]
I will test it out again tomorrow and I'll give feedback.

**Comment by sayonaraLulw** [comment]
It's still not really working for me to be honest...

**Comment by TcNobo** [comment]
Using accounts that need the normal Android Mobile Authenticator app, and the Steam Desktop Authenticator program works fine for me... Do you have any steps to recreate this issue? Is it ONLY accounts that have Steam Mobile Authenticator, while the rest work?
Are you using anything special, such as settings or Steam-related Third-party programs?

**Comment by sayonaraLulw** [comment]
It only happens with accounts which got Mobile Auth.. doesn't matter if it's with the Desktop App or Mobile App. Both don't work. It works with accs which don't have 2FA tho.

**Comment by TcNobo** [comment]
Closing. This should work. I can't recreate the issue myself, and this is the only report I have of it...
Do feel free to respond if you find more info.
