### ISSUE TITLE
Riot Switcher not working

### ISSUE THREAD

**Issue by Gorgrak** [TcNobo/TcNo-Acc-Switcher#82]
I'm back again. The issue I've been having still exists. Every so often (haven't been able to figure out how long) the switcher loses the credentials, meaning when I try to switch accounts it brings up a log-in screen with blank username and password fields. This issue occurs no matter how I utilize the utility (via shortcut, commandline, or even the Riot switcher itself). It always claims a successful switch. Attached is my most recent log detailing the error. No idea how to interpret it
[log.txt](https://github.com/TcNobo/TcNo-Acc-Switcher/files/7272777/log.txt)
.

**Comment by TcNobo** [comment]
Yes. The switcher doesn't remember credentials. It only swaps out a token that's saved after you log in. Whether the token is still valid is determined by Riot and their software/servers. The token is being swapped successfully, but whether it's valid isn't controlled by this software. 

Tokens do expire, and I've heard that logging in with more than 5 accounts can lead to them being invalidated... Not sure... Im Not sure what leads to them being invalid, but logging in again and saving the account fixes the issue.

**Comment by Gorgrak** [comment]
Oh yeah, oops; I meant to say the tokens aren't working. I only use 2 accounts so no idea what's wrong on their end. After an undetermined length of time, the token doesn't work anymore for the 2nd account. Basically, I've got a "smurf" account I use to play with my friends once every fortnight or so. When I try to switch over to it I have to re-enter my credentials and resave the tokens in the TcNo switcher.

Are you saying that someone has mentioned the token amnesia when having more than 5 accounts but other people are fine with less?

Also, were you able to determine anything from the log file I attached or did you already explain it to me in your response?

Thanks so much for making this utility!

**Comment by TcNobo** [comment]
This program ONLY:
- closes Riot game clients
- Swaps 'token' files
- launches Riot game clients (when one is clicked)

Log files and the rest from it are useless unfortunately. Unless I'm missing a file or something similar it should work almost flawlessly. Some platforms invalidate tokens for seemingly random reasons. On one before I missed a file that when not copied account switching only worked some of the time. I don't think I've done the same with the Riot switcher... I don't collect stats on switching accounts so I'm not sure of the success rate of everyone, unfortunately.

**Comment by Gorgrak** [comment]
Gotcha. Thank you for your time!

**Comment by TcNobo** [comment]
Please see the post linked above. The problem/s you've mentioned should be fixed with the next major update.
This issue is being closed and cleaned to prevent a flood of "x broken" posts.
