### ISSUE TITLE
Windows 11 Release: App is crushing at launch

### ISSUE THREAD

**Issue by AlexeyKuzhel** [TcNobo/TcNo-Acc-Switcher#83]
**Environment:**
Windows 11 Pro 21H2 with latest updates installed
Latest Switcher release 

**Steps to reproduce:**
1. Install application
2. Launch application 

**Actual result:**
App is crushing at launch. Please see attachments.
![image](https://user-images.githubusercontent.com/91922673/135938103-c0798775-8192-47c3-8f33-be9e8072b6e4.png)

**Note:**
I just installed MicrosoftEdge Web View 2. Application launched with the same error, but didn't close and looks like it works as in Win 10

**Comment by TcNobo** [comment]
([From the Wiki](https://github.com/TcNobo/TcNo-Acc-Switcher/wiki#1-installing-required-runtimes)) Make sure you have the latest from each of these downloaded and installed. I'll fire up a virtual machine with Win 11 tomorrow, but do see if this fixes it.

**Manual runtime install:**
-   **WebView2 Runtime:**  [Install](https://go.microsoft.com/fwlink/p/?LinkId=2124703).
-   **Microsoft .NET 5 Desktop Runtime:** [Download x64, under Run Desktop Apps](https://dotnet.microsoft.com/download/dotnet/5.0/runtime).
-   **ASP.NET Core 5 Runtime:** [Download Hosting Bundle, under Run Server Apps](https://dotnet.microsoft.com/download/dotnet/5.0/runtime).

The latest update of the TcNo Account Switcher uses the newest WebView2 - it doesn't give a required version... But it's working on Windows 10 with version 94.0.992.31. The latest from [Microsoft](https://developer.microsoft.com/en-us/microsoft-edge/webview2/) is 94.0.992.38.
This is my Control Panel, where it works on Windows 10.

![image](https://user-images.githubusercontent.com/10319195/135939588-d6174ac9-cf3f-459b-9c2d-dee375bc35e2.png)

**Comment by AlexeyKuzhel** [comment]
Just installed manually all the software from your comment and now everything working as expected without any errors. 
Thank you.

**Comment by TcNobo** [comment]
Awesome. Will check if there's something I can add better handle this error too :)
