### ISSUE TITLE
[Suggestion] GeForce Now

### ISSUE THREAD

**Issue by kotx** [TcNobo/TcNo-Acc-Switcher#90]
Because it's really annoying to log in and out of Steam while playing on GeForce Now, or have to switch accounts in GFN manually.

**Comment by TcNobo** [comment]
GeForce Now isn't available in South Africa... I can try to get account details, or borrow from you if this is possible ~ I am unfamiliar with this.

I'm assuming you've downloaded GeForce Now to your PC.
-  Do you want to switch GeForce Now accounts, or just your Steam account IN GeForce Now?
-  If Steam IN GeForce Now: Is it like other 'connect to a PC with Windows to game' or does it directly only launch games - no desktop interaction?

Hopefully I'm able to do some testing with just a free account. If you want to swap GeForce Now accounts this would be very easy - I assume.

**Comment by TcNobo** [comment]
Assuming you mean Steam IN GeForce Now -- This seems to be a web app of sorts... I would assume that Nvidia manages login tokens etc, to keep sync across devices. If this is the case, and the account is not stored locally, an account switcher would be very difficult if not near impossible to create.

**Comment by TcNobo** [comment]
I think this is the case, unfortunately:
![image](https://user-images.githubusercontent.com/10319195/140640577-eb669238-37ef-4e63-ac9d-28b83cbece6a.png)


Unless it's stored locally, this isn't so possible. You can use something like [SessionBox](https://chrome.google.com/webstore/detail/sessionbox-multi-login-to/megbklhjamjbcafknkgmokldgolkdfig?hl=en), or another cookie swapping plugin to swap between multiple Steam accounts - not needing a login (My program is similar to this, but for Windows).
Clicking Disconnect, then Connect, swapping Steam accounts using a plugin and then signing in seems like the fastest way.

**Comment by kotx** [comment]
Sorry for not being clear- if it's not possible to switch between Steam accounts in GeForce Now, I would prefer to be able to switch Nvidia accounts for the client locally.

**Comment by TcNobo** [comment]
Yeah switching linked accounts on GeForce now is not possible afaik. 
Is switching Nvidia accounts something people will use? I'm sure the cost would far outweigh the convenience of switching accounts...?

**Comment by kotx** [comment]
I dunno, just something I thought of because I needed it. But I'm on the free plan for both of my accounts so there isn't really a cost. 
I totally understand though if this isn't something that needs to be added, since it's not really a common problem. Up to you.

**Comment by TcNobo** [comment]
No, it should be easy enough to add. I'll add it to the list :)

**Comment by kkgamer18** [comment]
Just a bump for this suggestion

**Comment by TcNobo** [comment]
This platform was added with version 5.0 (Jan 2022). Please download and check if it works.
Re-open this issue if you have further comment :)

**Comment by kotx** [comment]
Seems to work fine!

**Comment by kkgamer18** [comment]
Yes working really good. Impressive work!
