### ISSUE TITLE
Cant run TCNO, .net required.

### ISSUE THREAD

**Issue by SirLanzelotHD** [TcNobo/TcNo-Acc-Switcher#91]
Each time i try to launch TCNO, the following error accures, "To run this application, you must install .NET."
i have following versions of .NET installed.

".NET runtimes installed:
Microsoft.AspNetCore.App 3.1.10
Microsoft.AspNetCore.App 5.0.7
Microsoft.AspNetCore.App 5.0.10
Microsoft.NETCore.App 3.1.10
Microsoft.NETCore.App 5.0.11
Microsoft.WindowsDesktop.App 5.0.11"

Kind regards
René

**Comment by TcNobo** [comment]
Super odd... I'd say download all 3 from here, if you haven't already https://github.com/TcNobo/TcNo-Acc-Switcher/wiki#1-installing-required-runtimes
Then install them again.
Maybe uninstall and reinstall if you're sure they're properly installed?

**Comment by SirLanzelotHD** [comment]
reinstalling didnt seem to work, i also tried using the _first_run_installer, but that did not work either.

**Comment by TcNobo** [comment]
Odd... Maybe try moving the actual files. If you installed it, try the portable version and extract it somewhere else?
There isn't much info here, unfortunately. Using missing or unreachable .NET files is simple to fix - That doesn't seem to be the case here.

**Comment by SirLanzelotHD** [comment]
Nope neither of them work.

**Comment by TcNobo** [comment]
Just checking up, have you had any luck with fixing this? There have been a few updates since this issue was created.

**Comment by TcNobo** [comment]
Closing this issue as stale.

**Comment by SirLanzelotHD** [comment]
i have not tried it until today, works like intended now. Thanks for the notification and great job, hope you´re doing well^^

**Comment by TcNobo** [comment]
Glad to know it works :)
