### ISSUE TITLE
Hide unused options

### ISSUE THREAD

**Issue by RadNotRed** [TcNobo/TcNo-Acc-Switcher#92]
Add the ability to hide useless options that you don't use.
PS. Discord switcher is useless now as discord has that feature themselves in beta.

**Comment by TcNobo** [comment]
Already implemented. Right-click the platform and `Hide platform`. You can get them back in Settings.
![image](https://user-images.githubusercontent.com/10319195/140834478-1cdbdabe-60f2-43f6-9783-db136c88426f.png)

**Comment by TcNobo** [comment]
Unless you mean actual options in the settings screen ~
Also, do you have a source for the discord switcher being built-in?

**Comment by RadNotRed** [comment]
ah thanks for showing how to hide it, didn't even try it.
I'll get the source on it when I have a chance

**Comment by RadNotRed** [comment]
This is what i have on it, its limited to a few people but it can be force enabled by discord. I'd just leave it as a feature until its rolled out to everybody by discord

![Screen Shot 2021-11-08 at 11 05 06 PM](https://user-images.githubusercontent.com/80015713/140860234-d96437b5-db1a-4ecc-8886-6d88444f18b4.png)
![Screen Shot 2021-11-08 at 11 04 48 PM](https://user-images.githubusercontent.com/80015713/140860240-7ce958b3-909a-4573-9e00-b63d60acbba1.png)
![Screen Shot 2021-11-08 at 11 04 42 PM](https://user-images.githubusercontent.com/80015713/140860252-e7d80145-3baa-477c-b1ee-62bf4d6f2f9d.png)

**Comment by TcNobo** [comment]
Oh, obviously. I won't be removing it unless it breaks it. I'm sure there is still no protection on your account token... Unlike there is with this program :)
