### ISSUE TITLE
Riot doesn't work??

### ISSUE THREAD

**Issue by LIGHTUPSKECHERS** [TcNobo/TcNo-Acc-Switcher#93]
I'm trying the riot client thing and its not working whenever I press on the accounts it just logs me out

**Comment by TcNobo** [comment]
Unfortunately seems to work for me... What game in particular?
Try removing the account, clicking New, signing in again with Remember Password checked, and see if it works from there ~

**Comment by TcNobo** [comment]
I am unable to replicate this issue with Valorant and League of Legends.

**Comment by TcNobo** [comment]
If you can provide more information on how to recreate this issue, I am able to help. This works on Windows 10 & 11.

**Comment by jordanyoong1** [comment]
https://user-images.githubusercontent.com/40160073/142198734-81ce49c1-111a-4954-84dc-215bad56d21f.mp4

I have the same issue aswell

**Comment by TcNobo** [comment]
@jordanyoong1 Clicking "Sign Out" in any Riot Client will deactivate your token on your computer - The one that is saved and swapped out by the account switcher.

Do NOT click Sign Out in any game/launcher, rather use the "+ Add New" button in the account switcher to log into a new account.

This should get everything working :)

**Comment by jordanyoong1** [comment]
> @jordanyoong1 Clicking "Sign Out" in any Riot Client will deactivate your token on your computer - The one that is saved and swapped out by the account switcher.
> 
> Do NOT click Sign Out in any game/launcher, rather use the "+ Add New" button in the account switcher to log into a new account.
> 
> This should get everything working :)

Thanks, this works. But for some reason, there's one specific account that I couldn't get it work. When I activate that account, my RiotClientPrivateSettings.yaml turns into
```
private:
    riot-login:
        persist: null

```
Any other account works

**Comment by TcNobo** [comment]
Please see the post linked above. The problem/s you've mentioned should be fixed with the next major update.
This issue is being closed and cleaned to prevent a flood of "x broken" posts.
