### ISSUE TITLE
Epic Launcher Setting wants upc.exe location in Build 2021-09-28_00

### ISSUE THREAD

**Issue by kartana** [TcNobo/TcNo-Acc-Switcher#98]
Build 2021-09-28_00 doesn't work with Epic for me. After selecting the .exe and then clicking the "+ Add New" nothing happens. This might be related to that when I click on Epic and then the gear to go to the options and then click "Pick Epic Folder" it wants the upc.exe which is from the Ubisoft Launcher.

**Comment by TcNobo** [comment]
This is fixed with the latest release, here: https://github.com/TcNobo/TcNo-Acc-Switcher/releases/tag/2021-11-20_00
Let me know if this fixed the issue.

**Comment by kartana** [comment]
Seems to work fine now I think. Thanks
