### ISSUE TITLE
Issues and wrong translations in Arabic language

### ISSUE THREAD

**Issue by Majoramari** [TcNobo/TcNo-Acc-Switcher#99]
## Why this issue importent? (You could escape it)
Around 35% of Egypt's population speak English fairly good, but it's not the case in the majority of the Arabian countries... and looks like the translation of this softwere has some issues

---

## Misleading/Meaningless translations
Looks like the translations done with Google Translate.

Some example:
"تشغيل BattleNet كمشرف"
"مفتاح اختصار سطح المكتب BattleNet"
"إظهاراسم الحساب [ليس اسم صديق]"

It's so hard to understand what does this mean for a normal user.

 I could contribute to translate and review the Arabic translation If is that okay, I'm a native Arabic speaker. [crowdin profile](https://crowdin.com/profile/majoramari)

## Wrong title (The one in the drop down menu)!
The title claims to be Saudi Arabia's accent… Obviously it's not, it's Standard Arabic language. So the title should be changed to **Arabic** instead of **Arabic (Saudi Arabia)**.

**_NOTE: No need to add other Arabic accents because almost all Arabian countries know the standard Arabic regardless of their accent. (e.g., Egypt, Saudi Arabia, UAE, ETC)_**

## Arabic is a Right to left language

The Arabic is RTL and the app is LTR so if there is any sentence contain English, it messes the whole sentence plus it's not the natural way to read Arabic

**_NOTE: this also apply to any other RTL language like Hebrew!_**

### The way it is now
![image](https://user-images.githubusercontent.com/33487552/142768416-ec6cdd84-67f7-4de9-9ea6-33045981f8a8.png)

### it should be something like this (almost):
![image](https://user-images.githubusercontent.com/33487552/142768577-ef0d2fce-306b-43e8-9305-a74bbf0e06a6.png)

**Comment by TcNobo** [comment]
Translations were all auto-generated with Crowdin's machine learning system. You're welcome to help. It is open and I'd love for communities to help https://crowdin.com/project/tcno-account-switcher.

I have promoted you to Proofreader, you can approve translations in Arabic now.

As for RTL, I haven't looked into it. Everything is currently coded to be one way round (styling), it will take some tweaking to get things looking right in RTL as they do in LTR. This is something I shall work on though :)

**Comment by Majoramari** [comment]
@TcNobo 

> I have promoted you to Proofreader, you can approve translations in Arabic now.

Thanks i'll do my best in translation.

> As for RTL, I haven't looked into it. Everything is currently coded to be one way round (styling), it will take some tweaking to get things looking right in RTL as they do in LTR. This is something I shall work on though :)

I'm not sure what is the best way, but one way came to my mine is making a default RTL theme, so we need a functionality to link a language to a default theme I think.

**Comment by TcNobo** [comment]
Looks awesome!
I will look into your changes for RTL, and implement a toggle in the main program to achieve similar things ~ with any skin.

Thanks for your help!

**Comment by TcNobo** [comment]
The next update will have an RTL toggle, which automatically enables/disables with language change.
I'll remove the RTL copy of your theme from the theme repo in a bit, and then add your theme to the official themes distributed with the program.

Implemented your code, here: https://github.com/TcNobo/TcNo-Acc-Switcher/commit/1b7e670c78688826ad148f5a648fd52f725dc642#diff-d8f974ee170c7d0b97924700445c332309fd48a37d8c64b317f51abe365d7dc9

![cck8TkO2NC](https://user-images.githubusercontent.com/10319195/143782184-2ea5c2a5-4a5a-4ec1-8c9d-4a0556e2f403.png)

**Comment by TcNobo** [comment]
Alright, everything is now in the full release. https://github.com/TcNobo/TcNo-Acc-Switcher/releases/tag/2021-12-06_00
Proper RTL support, at least from what I can tell, is added. Your theme is also officially included with all builds now too.

Thanks again for the help.
Also, I've added a 'credits' window right next to the Help Translate button.
